// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/requestlog"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// RequestLogCreate is the builder for creating a RequestLog entity.
type RequestLogCreate struct {
	config
	mutation *RequestLogMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *RequestLogCreate) SetUserID(v int64) *RequestLogCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *RequestLogCreate) SetAPIKeyID(v int64) *RequestLogCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetRequestID sets the "request_id" field.
func (_c *RequestLogCreate) SetRequestID(v string) *RequestLogCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_c *RequestLogCreate) SetNillableRequestID(v *string) *RequestLogCreate {
	if v != nil {
		_c.SetRequestID(*v)
	}
	return _c
}

// SetModel sets the "model" field.
func (_c *RequestLogCreate) SetModel(v string) *RequestLogCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetInboundEndpoint sets the "inbound_endpoint" field.
func (_c *RequestLogCreate) SetInboundEndpoint(v string) *RequestLogCreate {
	_c.mutation.SetInboundEndpoint(v)
	return _c
}

// SetNillableInboundEndpoint sets the "inbound_endpoint" field if the given value is not nil.
func (_c *RequestLogCreate) SetNillableInboundEndpoint(v *string) *RequestLogCreate {
	if v != nil {
		_c.SetInboundEndpoint(*v)
	}
	return _c
}

// SetUpstreamEndpoint sets the "upstream_endpoint" field.
func (_c *RequestLogCreate) SetUpstreamEndpoint(v string) *RequestLogCreate {
	_c.mutation.SetUpstreamEndpoint(v)
	return _c
}

// SetNillableUpstreamEndpoint sets the "upstream_endpoint" field if the given value is not nil.
func (_c *RequestLogCreate) SetNillableUpstreamEndpoint(v *string) *RequestLogCreate {
	if v != nil {
		_c.SetUpstreamEndpoint(*v)
	}
	return _c
}

// SetMethod sets the "method" field.
func (_c *RequestLogCreate) SetMethod(v string) *RequestLogCreate {
	_c.mutation.SetMethod(v)
	return _c
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_c *RequestLogCreate) SetNillableMethod(v *string) *RequestLogCreate {
	if v != nil {
		_c.SetMethod(*v)
	}
	return _c
}

// SetStatusCode sets the "status_code" field.
func (_c *RequestLogCreate) SetStatusCode(v int) *RequestLogCreate {
	_c.mutation.SetStatusCode(v)
	return _c
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_c *RequestLogCreate) SetNillableStatusCode(v *int) *RequestLogCreate {
	if v != nil {
		_c.SetStatusCode(*v)
	}
	return _c
}

// SetErrorCode sets the "error_code" field.
func (_c *RequestLogCreate) SetErrorCode(v string) *RequestLogCreate {
	_c.mutation.SetErrorCode(v)
	return _c
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_c *RequestLogCreate) SetNillableErrorCode(v *string) *RequestLogCreate {
	if v != nil {
		_c.SetErrorCode(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *RequestLogCreate) SetErrorMessage(v string) *RequestLogCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *RequestLogCreate) SetNillableErrorMessage(v *string) *RequestLogCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetInputTokens sets the "input_tokens" field.
func (_c *RequestLogCreate) SetInputTokens(v int) *RequestLogCreate {
	_c.mutation.SetInputTokens(v)
	return _c
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_c *RequestLogCreate) SetNillableInputTokens(v *int) *RequestLogCreate {
	if v != nil {
		_c.SetInputTokens(*v)
	}
	return _c
}

// SetOutputTokens sets the "output_tokens" field.
func (_c *RequestLogCreate) SetOutputTokens(v int) *RequestLogCreate {
	_c.mutation.SetOutputTokens(v)
	return _c
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_c *RequestLogCreate) SetNillableOutputTokens(v *int) *RequestLogCreate {
	if v != nil {
		_c.SetOutputTokens(*v)
	}
	return _c
}

// SetTotalCost sets the "total_cost" field.
func (_c *RequestLogCreate) SetTotalCost(v float64) *RequestLogCreate {
	_c.mutation.SetTotalCost(v)
	return _c
}

// SetNillableTotalCost sets the "total_cost" field if the given value is not nil.
func (_c *RequestLogCreate) SetNillableTotalCost(v *float64) *RequestLogCreate {
	if v != nil {
		_c.SetTotalCost(*v)
	}
	return _c
}

// SetStream sets the "stream" field.
func (_c *RequestLogCreate) SetStream(v bool) *RequestLogCreate {
	_c.mutation.SetStream(v)
	return _c
}

// SetNillableStream sets the "stream" field if the given value is not nil.
func (_c *RequestLogCreate) SetNillableStream(v *bool) *RequestLogCreate {
	if v != nil {
		_c.SetStream(*v)
	}
	return _c
}

// SetDurationMs sets the "duration_ms" field.
func (_c *RequestLogCreate) SetDurationMs(v int) *RequestLogCreate {
	_c.mutation.SetDurationMs(v)
	return _c
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_c *RequestLogCreate) SetNillableDurationMs(v *int) *RequestLogCreate {
	if v != nil {
		_c.SetDurationMs(*v)
	}
	return _c
}

// SetFirstTokenMs sets the "first_token_ms" field.
func (_c *RequestLogCreate) SetFirstTokenMs(v int) *RequestLogCreate {
	_c.mutation.SetFirstTokenMs(v)
	return _c
}

// SetNillableFirstTokenMs sets the "first_token_ms" field if the given value is not nil.
func (_c *RequestLogCreate) SetNillableFirstTokenMs(v *int) *RequestLogCreate {
	if v != nil {
		_c.SetFirstTokenMs(*v)
	}
	return _c
}

// SetUserAgent sets the "user_agent" field.
func (_c *RequestLogCreate) SetUserAgent(v string) *RequestLogCreate {
	_c.mutation.SetUserAgent(v)
	return _c
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_c *RequestLogCreate) SetNillableUserAgent(v *string) *RequestLogCreate {
	if v != nil {
		_c.SetUserAgent(*v)
	}
	return _c
}

// SetIPAddress sets the "ip_address" field.
func (_c *RequestLogCreate) SetIPAddress(v string) *RequestLogCreate {
	_c.mutation.SetIPAddress(v)
	return _c
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_c *RequestLogCreate) SetNillableIPAddress(v *string) *RequestLogCreate {
	if v != nil {
		_c.SetIPAddress(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RequestLogCreate) SetCreatedAt(v time.Time) *RequestLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RequestLogCreate) SetNillableCreatedAt(v *time.Time) *RequestLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *RequestLogCreate) SetUser(v *User) *RequestLogCreate {
	return _c.SetUserID(v.ID)
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_c *RequestLogCreate) SetAPIKey(v *APIKey) *RequestLogCreate {
	return _c.SetAPIKeyID(v.ID)
}

// Mutation returns the RequestLogMutation object of the builder.
func (_c *RequestLogCreate) Mutation() *RequestLogMutation {
	return _c.mutation
}

// Save creates the RequestLog in the database.
func (_c *RequestLogCreate) Save(ctx context.Context) (*RequestLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RequestLogCreate) SaveX(ctx context.Context) *RequestLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RequestLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RequestLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RequestLogCreate) defaults() {
	if _, ok := _c.mutation.InputTokens(); !ok {
		v := requestlog.DefaultInputTokens
		_c.mutation.SetInputTokens(v)
	}
	if _, ok := _c.mutation.OutputTokens(); !ok {
		v := requestlog.DefaultOutputTokens
		_c.mutation.SetOutputTokens(v)
	}
	if _, ok := _c.mutation.TotalCost(); !ok {
		v := requestlog.DefaultTotalCost
		_c.mutation.SetTotalCost(v)
	}
	if _, ok := _c.mutation.Stream(); !ok {
		v := requestlog.DefaultStream
		_c.mutation.SetStream(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := requestlog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RequestLogCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "RequestLog.user_id"`)}
	}
	if _, ok := _c.mutation.APIKeyID(); !ok {
		return &ValidationError{Name: "api_key_id", err: errors.New(`ent: missing required field "RequestLog.api_key_id"`)}
	}
	if v, ok := _c.mutation.RequestID(); ok {
		if err := requestlog.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "RequestLog.request_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "RequestLog.model"`)}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := requestlog.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "RequestLog.model": %w`, err)}
		}
	}
	if v, ok := _c.mutation.InboundEndpoint(); ok {
		if err := requestlog.InboundEndpointValidator(v); err != nil {
			return &ValidationError{Name: "inbound_endpoint", err: fmt.Errorf(`ent: validator failed for field "RequestLog.inbound_endpoint": %w`, err)}
		}
	}
	if v, ok := _c.mutation.UpstreamEndpoint(); ok {
		if err := requestlog.UpstreamEndpointValidator(v); err != nil {
			return &ValidationError{Name: "upstream_endpoint", err: fmt.Errorf(`ent: validator failed for field "RequestLog.upstream_endpoint": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Method(); ok {
		if err := requestlog.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "RequestLog.method": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ErrorCode(); ok {
		if err := requestlog.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "RequestLog.error_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.InputTokens(); !ok {
		return &ValidationError{Name: "input_tokens", err: errors.New(`ent: missing required field "RequestLog.input_tokens"`)}
	}
	if _, ok := _c.mutation.OutputTokens(); !ok {
		return &ValidationError{Name: "output_tokens", err: errors.New(`ent: missing required field "RequestLog.output_tokens"`)}
	}
	if _, ok := _c.mutation.TotalCost(); !ok {
		return &ValidationError{Name: "total_cost", err: errors.New(`ent: missing required field "RequestLog.total_cost"`)}
	}
	if _, ok := _c.mutation.Stream(); !ok {
		return &ValidationError{Name: "stream", err: errors.New(`ent: missing required field "RequestLog.stream"`)}
	}
	if v, ok := _c.mutation.UserAgent(); ok {
		if err := requestlog.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "RequestLog.user_agent": %w`, err)}
		}
	}
	if v, ok := _c.mutation.IPAddress(); ok {
		if err := requestlog.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf(`ent: validator failed for field "RequestLog.ip_address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RequestLog.created_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "RequestLog.user"`)}
	}
	if len(_c.mutation.APIKeyIDs()) == 0 {
		return &ValidationError{Name: "api_key", err: errors.New(`ent: missing required edge "RequestLog.api_key"`)}
	}
	return nil
}

func (_c *RequestLogCreate) sqlSave(ctx context.Context) (*RequestLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RequestLogCreate) createSpec() (*RequestLog, *sqlgraph.CreateSpec) {
	var (
		_node = &RequestLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(requestlog.Table, sqlgraph.NewFieldSpec(requestlog.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(requestlog.FieldRequestID, field.TypeString, value)
		_node.RequestID = &value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(requestlog.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.InboundEndpoint(); ok {
		_spec.SetField(requestlog.FieldInboundEndpoint, field.TypeString, value)
		_node.InboundEndpoint = &value
	}
	if value, ok := _c.mutation.UpstreamEndpoint(); ok {
		_spec.SetField(requestlog.FieldUpstreamEndpoint, field.TypeString, value)
		_node.UpstreamEndpoint = &value
	}
	if value, ok := _c.mutation.Method(); ok {
		_spec.SetField(requestlog.FieldMethod, field.TypeString, value)
		_node.Method = &value
	}
	if value, ok := _c.mutation.StatusCode(); ok {
		_spec.SetField(requestlog.FieldStatusCode, field.TypeInt, value)
		_node.StatusCode = &value
	}
	if value, ok := _c.mutation.ErrorCode(); ok {
		_spec.SetField(requestlog.FieldErrorCode, field.TypeString, value)
		_node.ErrorCode = &value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(requestlog.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = &value
	}
	if value, ok := _c.mutation.InputTokens(); ok {
		_spec.SetField(requestlog.FieldInputTokens, field.TypeInt, value)
		_node.InputTokens = value
	}
	if value, ok := _c.mutation.OutputTokens(); ok {
		_spec.SetField(requestlog.FieldOutputTokens, field.TypeInt, value)
		_node.OutputTokens = value
	}
	if value, ok := _c.mutation.TotalCost(); ok {
		_spec.SetField(requestlog.FieldTotalCost, field.TypeFloat64, value)
		_node.TotalCost = value
	}
	if value, ok := _c.mutation.Stream(); ok {
		_spec.SetField(requestlog.FieldStream, field.TypeBool, value)
		_node.Stream = value
	}
	if value, ok := _c.mutation.DurationMs(); ok {
		_spec.SetField(requestlog.FieldDurationMs, field.TypeInt, value)
		_node.DurationMs = &value
	}
	if value, ok := _c.mutation.FirstTokenMs(); ok {
		_spec.SetField(requestlog.FieldFirstTokenMs, field.TypeInt, value)
		_node.FirstTokenMs = &value
	}
	if value, ok := _c.mutation.UserAgent(); ok {
		_spec.SetField(requestlog.FieldUserAgent, field.TypeString, value)
		_node.UserAgent = &value
	}
	if value, ok := _c.mutation.IPAddress(); ok {
		_spec.SetField(requestlog.FieldIPAddress, field.TypeString, value)
		_node.IPAddress = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(requestlog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   requestlog.UserTable,
			Columns: []string{requestlog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   requestlog.APIKeyTable,
			Columns: []string{requestlog.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.APIKeyID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RequestLog.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RequestLogUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *RequestLogCreate) OnConflict(opts ...sql.ConflictOption) *RequestLogUpsertOne {
	_c.conflict = opts
	return &RequestLogUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RequestLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RequestLogCreate) OnConflictColumns(columns ...string) *RequestLogUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RequestLogUpsertOne{
		create: _c,
	}
}

type (
	// RequestLogUpsertOne is the builder for "upsert"-ing
	//  one RequestLog node.
	RequestLogUpsertOne struct {
		create *RequestLogCreate
	}

	// RequestLogUpsert is the "OnConflict" setter.
	RequestLogUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *RequestLogUpsert) SetUserID(v int64) *RequestLogUpsert {
	u.Set(requestlog.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RequestLogUpsert) UpdateUserID() *RequestLogUpsert {
	u.SetExcluded(requestlog.FieldUserID)
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *RequestLogUpsert) SetAPIKeyID(v int64) *RequestLogUpsert {
	u.Set(requestlog.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *RequestLogUpsert) UpdateAPIKeyID() *RequestLogUpsert {
	u.SetExcluded(requestlog.FieldAPIKeyID)
	return u
}

// SetRequestID sets the "request_id" field.
func (u *RequestLogUpsert) SetRequestID(v string) *RequestLogUpsert {
	u.Set(requestlog.FieldRequestID, v)
	return u
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *RequestLogUpsert) UpdateRequestID() *RequestLogUpsert {
	u.SetExcluded(requestlog.FieldRequestID)
	return u
}

// ClearRequestID clears the value of the "request_id" field.
func (u *RequestLogUpsert) ClearRequestID() *RequestLogUpsert {
	u.SetNull(requestlog.FieldRequestID)
	return u
}

// SetModel sets the "model" field.
func (u *RequestLogUpsert) SetModel(v string) *RequestLogUpsert {
	u.Set(requestlog.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *RequestLogUpsert) UpdateModel() *RequestLogUpsert {
	u.SetExcluded(requestlog.FieldModel)
	return u
}

// SetInboundEndpoint sets the "inbound_endpoint" field.
func (u *RequestLogUpsert) SetInboundEndpoint(v string) *RequestLogUpsert {
	u.Set(requestlog.FieldInboundEndpoint, v)
	return u
}

// UpdateInboundEndpoint sets the "inbound_endpoint" field to the value that was provided on create.
func (u *RequestLogUpsert) UpdateInboundEndpoint() *RequestLogUpsert {
	u.SetExcluded(requestlog.FieldInboundEndpoint)
	return u
}

// ClearInboundEndpoint clears the value of the "inbound_endpoint" field.
func (u *RequestLogUpsert) ClearInboundEndpoint() *RequestLogUpsert {
	u.SetNull(requestlog.FieldInboundEndpoint)
	return u
}

// SetUpstreamEndpoint sets the "upstream_endpoint" field.
func (u *RequestLogUpsert) SetUpstreamEndpoint(v string) *RequestLogUpsert {
	u.Set(requestlog.FieldUpstreamEndpoint, v)
	return u
}

// UpdateUpstreamEndpoint sets the "upstream_endpoint" field to the value that was provided on create.
func (u *RequestLogUpsert) UpdateUpstreamEndpoint() *RequestLogUpsert {
	u.SetExcluded(requestlog.FieldUpstreamEndpoint)
	return u
}

// ClearUpstreamEndpoint clears the value of the "upstream_endpoint" field.
func (u *RequestLogUpsert) ClearUpstreamEndpoint() *RequestLogUpsert {
	u.SetNull(requestlog.FieldUpstreamEndpoint)
	return u
}

// SetMethod sets the "method" field.
func (u *RequestLogUpsert) SetMethod(v string) *RequestLogUpsert {
	u.Set(requestlog.FieldMethod, v)
	return u
}

// UpdateMethod sets the "method" field to the value that was provided on create.
func (u *RequestLogUpsert) UpdateMethod() *RequestLogUpsert {
	u.SetExcluded(requestlog.FieldMethod)
	return u
}

// ClearMethod clears the value of the "method" field.
func (u *RequestLogUpsert) ClearMethod() *RequestLogUpsert {
	u.SetNull(requestlog.FieldMethod)
	return u
}

// SetStatusCode sets the "status_code" field.
func (u *RequestLogUpsert) SetStatusCode(v int) *RequestLogUpsert {
	u.Set(requestlog.FieldStatusCode, v)
	return u
}

// UpdateStatusCode sets the "status_code" field to the value that was provided on create.
func (u *RequestLogUpsert) UpdateStatusCode() *RequestLogUpsert {
	u.SetExcluded(requestlog.FieldStatusCode)
	return u
}

// AddStatusCode adds v to the "status_code" field.
func (u *RequestLogUpsert) AddStatusCode(v int) *RequestLogUpsert {
	u.Add(requestlog.FieldStatusCode, v)
	return u
}

// ClearStatusCode clears the value of the "status_code" field.
func (u *RequestLogUpsert) ClearStatusCode() *RequestLogUpsert {
	u.SetNull(requestlog.FieldStatusCode)
	return u
}

// SetErrorCode sets the "error_code" field.
func (u *RequestLogUpsert) SetErrorCode(v string) *RequestLogUpsert {
	u.Set(requestlog.FieldErrorCode, v)
	return u
}

// UpdateErrorCode sets the "error_code" field to the value that was provided on create.
func (u *RequestLogUpsert) UpdateErrorCode() *RequestLogUpsert {
	u.SetExcluded(requestlog.FieldErrorCode)
	return u
}

// ClearErrorCode clears the value of the "error_code" field.
func (u *RequestLogUpsert) ClearErrorCode() *RequestLogUpsert {
	u.SetNull(requestlog.FieldErrorCode)
	return u
}

// SetErrorMessage sets the "error_message" field.
func (u *RequestLogUpsert) SetErrorMessage(v string) *RequestLogUpsert {
	u.Set(requestlog.FieldErrorMessage, v)
	return u
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *RequestLogUpsert) UpdateErrorMessage() *RequestLogUpsert {
	u.SetExcluded(requestlog.FieldErrorMessage)
	return u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *RequestLogUpsert) ClearErrorMessage() *RequestLogUpsert {
	u.SetNull(requestlog.FieldErrorMessage)
	return u
}

// SetInputTokens sets the "input_tokens" field.
func (u *RequestLogUpsert) SetInputTokens(v int) *RequestLogUpsert {
	u.Set(requestlog.FieldInputTokens, v)
	return u
}

// UpdateInputTokens sets the "input_tokens" field to the value that was provided on create.
func (u *RequestLogUpsert) UpdateInputTokens() *RequestLogUpsert {
	u.SetExcluded(requestlog.FieldInputTokens)
	return u
}

// AddInputTokens adds v to the "input_tokens" field.
func (u *RequestLogUpsert) AddInputTokens(v int) *RequestLogUpsert {
	u.Add(requestlog.FieldInputTokens, v)
	return u
}

// SetOutputTokens sets the "output_tokens" field.
func (u *RequestLogUpsert) SetOutputTokens(v int) *RequestLogUpsert {
	u.Set(requestlog.FieldOutputTokens, v)
	return u
}

// UpdateOutputTokens sets the "output_tokens" field to the value that was provided on create.
func (u *RequestLogUpsert) UpdateOutputTokens() *RequestLogUpsert {
	u.SetExcluded(requestlog.FieldOutputTokens)
	return u
}

// AddOutputTokens adds v to the "output_tokens" field.
func (u *RequestLogUpsert) AddOutputTokens(v int) *RequestLogUpsert {
	u.Add(requestlog.FieldOutputTokens, v)
	return u
}

// SetTotalCost sets the "total_cost" field.
func (u *RequestLogUpsert) SetTotalCost(v float64) *RequestLogUpsert {
	u.Set(requestlog.FieldTotalCost, v)
	return u
}

// UpdateTotalCost sets the "total_cost" field to the value that was provided on create.
func (u *RequestLogUpsert) UpdateTotalCost() *RequestLogUpsert {
	u.SetExcluded(requestlog.FieldTotalCost)
	return u
}

// AddTotalCost adds v to the "total_cost" field.
func (u *RequestLogUpsert) AddTotalCost(v float64) *RequestLogUpsert {
	u.Add(requestlog.FieldTotalCost, v)
	return u
}

// SetStream sets the "stream" field.
func (u *RequestLogUpsert) SetStream(v bool) *RequestLogUpsert {
	u.Set(requestlog.FieldStream, v)
	return u
}

// UpdateStream sets the "stream" field to the value that was provided on create.
func (u *RequestLogUpsert) UpdateStream() *RequestLogUpsert {
	u.SetExcluded(requestlog.FieldStream)
	return u
}

// SetDurationMs sets the "duration_ms" field.
func (u *RequestLogUpsert) SetDurationMs(v int) *RequestLogUpsert {
	u.Set(requestlog.FieldDurationMs, v)
	return u
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *RequestLogUpsert) UpdateDurationMs() *RequestLogUpsert {
	u.SetExcluded(requestlog.FieldDurationMs)
	return u
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *RequestLogUpsert) AddDurationMs(v int) *RequestLogUpsert {
	u.Add(requestlog.FieldDurationMs, v)
	return u
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (u *RequestLogUpsert) ClearDurationMs() *RequestLogUpsert {
	u.SetNull(requestlog.FieldDurationMs)
	return u
}

// SetFirstTokenMs sets the "first_token_ms" field.
func (u *RequestLogUpsert) SetFirstTokenMs(v int) *RequestLogUpsert {
	u.Set(requestlog.FieldFirstTokenMs, v)
	return u
}

// UpdateFirstTokenMs sets the "first_token_ms" field to the value that was provided on create.
func (u *RequestLogUpsert) UpdateFirstTokenMs() *RequestLogUpsert {
	u.SetExcluded(requestlog.FieldFirstTokenMs)
	return u
}

// AddFirstTokenMs adds v to the "first_token_ms" field.
func (u *RequestLogUpsert) AddFirstTokenMs(v int) *RequestLogUpsert {
	u.Add(requestlog.FieldFirstTokenMs, v)
	return u
}

// ClearFirstTokenMs clears the value of the "first_token_ms" field.
func (u *RequestLogUpsert) ClearFirstTokenMs() *RequestLogUpsert {
	u.SetNull(requestlog.FieldFirstTokenMs)
	return u
}

// SetUserAgent sets the "user_agent" field.
func (u *RequestLogUpsert) SetUserAgent(v string) *RequestLogUpsert {
	u.Set(requestlog.FieldUserAgent, v)
	return u
}

// UpdateUserAgent sets the "user_agent" field to the value that was provided on create.
func (u *RequestLogUpsert) UpdateUserAgent() *RequestLogUpsert {
	u.SetExcluded(requestlog.FieldUserAgent)
	return u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (u *RequestLogUpsert) ClearUserAgent() *RequestLogUpsert {
	u.SetNull(requestlog.FieldUserAgent)
	return u
}

// SetIPAddress sets the "ip_address" field.
func (u *RequestLogUpsert) SetIPAddress(v string) *RequestLogUpsert {
	u.Set(requestlog.FieldIPAddress, v)
	return u
}

// UpdateIPAddress sets the "ip_address" field to the value that was provided on create.
func (u *RequestLogUpsert) UpdateIPAddress() *RequestLogUpsert {
	u.SetExcluded(requestlog.FieldIPAddress)
	return u
}

// ClearIPAddress clears the value of the "ip_address" field.
func (u *RequestLogUpsert) ClearIPAddress() *RequestLogUpsert {
	u.SetNull(requestlog.FieldIPAddress)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.RequestLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RequestLogUpsertOne) UpdateNewValues() *RequestLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(requestlog.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RequestLog.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RequestLogUpsertOne) Ignore() *RequestLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RequestLogUpsertOne) DoNothing() *RequestLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RequestLogCreate.OnConflict
// documentation for more info.
func (u *RequestLogUpsertOne) Update(set func(*RequestLogUpsert)) *RequestLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RequestLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *RequestLogUpsertOne) SetUserID(v int64) *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RequestLogUpsertOne) UpdateUserID() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *RequestLogUpsertOne) SetAPIKeyID(v int64) *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *RequestLogUpsertOne) UpdateAPIKeyID() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetRequestID sets the "request_id" field.
func (u *RequestLogUpsertOne) SetRequestID(v string) *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *RequestLogUpsertOne) UpdateRequestID() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateRequestID()
	})
}

// ClearRequestID clears the value of the "request_id" field.
func (u *RequestLogUpsertOne) ClearRequestID() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.ClearRequestID()
	})
}

// SetModel sets the "model" field.
func (u *RequestLogUpsertOne) SetModel(v string) *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *RequestLogUpsertOne) UpdateModel() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateModel()
	})
}

// SetInboundEndpoint sets the "inbound_endpoint" field.
func (u *RequestLogUpsertOne) SetInboundEndpoint(v string) *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetInboundEndpoint(v)
	})
}

// UpdateInboundEndpoint sets the "inbound_endpoint" field to the value that was provided on create.
func (u *RequestLogUpsertOne) UpdateInboundEndpoint() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateInboundEndpoint()
	})
}

// ClearInboundEndpoint clears the value of the "inbound_endpoint" field.
func (u *RequestLogUpsertOne) ClearInboundEndpoint() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.ClearInboundEndpoint()
	})
}

// SetUpstreamEndpoint sets the "upstream_endpoint" field.
func (u *RequestLogUpsertOne) SetUpstreamEndpoint(v string) *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetUpstreamEndpoint(v)
	})
}

// UpdateUpstreamEndpoint sets the "upstream_endpoint" field to the value that was provided on create.
func (u *RequestLogUpsertOne) UpdateUpstreamEndpoint() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateUpstreamEndpoint()
	})
}

// ClearUpstreamEndpoint clears the value of the "upstream_endpoint" field.
func (u *RequestLogUpsertOne) ClearUpstreamEndpoint() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.ClearUpstreamEndpoint()
	})
}

// SetMethod sets the "method" field.
func (u *RequestLogUpsertOne) SetMethod(v string) *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetMethod(v)
	})
}

// UpdateMethod sets the "method" field to the value that was provided on create.
func (u *RequestLogUpsertOne) UpdateMethod() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateMethod()
	})
}

// ClearMethod clears the value of the "method" field.
func (u *RequestLogUpsertOne) ClearMethod() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.ClearMethod()
	})
}

// SetStatusCode sets the "status_code" field.
func (u *RequestLogUpsertOne) SetStatusCode(v int) *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetStatusCode(v)
	})
}

// AddStatusCode adds v to the "status_code" field.
func (u *RequestLogUpsertOne) AddStatusCode(v int) *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.AddStatusCode(v)
	})
}

// UpdateStatusCode sets the "status_code" field to the value that was provided on create.
func (u *RequestLogUpsertOne) UpdateStatusCode() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateStatusCode()
	})
}

// ClearStatusCode clears the value of the "status_code" field.
func (u *RequestLogUpsertOne) ClearStatusCode() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.ClearStatusCode()
	})
}

// SetErrorCode sets the "error_code" field.
func (u *RequestLogUpsertOne) SetErrorCode(v string) *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetErrorCode(v)
	})
}

// UpdateErrorCode sets the "error_code" field to the value that was provided on create.
func (u *RequestLogUpsertOne) UpdateErrorCode() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateErrorCode()
	})
}

// ClearErrorCode clears the value of the "error_code" field.
func (u *RequestLogUpsertOne) ClearErrorCode() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.ClearErrorCode()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *RequestLogUpsertOne) SetErrorMessage(v string) *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *RequestLogUpsertOne) UpdateErrorMessage() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *RequestLogUpsertOne) ClearErrorMessage() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.ClearErrorMessage()
	})
}

// SetInputTokens sets the "input_tokens" field.
func (u *RequestLogUpsertOne) SetInputTokens(v int) *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetInputTokens(v)
	})
}

// AddInputTokens adds v to the "input_tokens" field.
func (u *RequestLogUpsertOne) AddInputTokens(v int) *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.AddInputTokens(v)
	})
}

// UpdateInputTokens sets the "input_tokens" field to the value that was provided on create.
func (u *RequestLogUpsertOne) UpdateInputTokens() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateInputTokens()
	})
}

// SetOutputTokens sets the "output_tokens" field.
func (u *RequestLogUpsertOne) SetOutputTokens(v int) *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetOutputTokens(v)
	})
}

// AddOutputTokens adds v to the "output_tokens" field.
func (u *RequestLogUpsertOne) AddOutputTokens(v int) *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.AddOutputTokens(v)
	})
}

// UpdateOutputTokens sets the "output_tokens" field to the value that was provided on create.
func (u *RequestLogUpsertOne) UpdateOutputTokens() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateOutputTokens()
	})
}

// SetTotalCost sets the "total_cost" field.
func (u *RequestLogUpsertOne) SetTotalCost(v float64) *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetTotalCost(v)
	})
}

// AddTotalCost adds v to the "total_cost" field.
func (u *RequestLogUpsertOne) AddTotalCost(v float64) *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.AddTotalCost(v)
	})
}

// UpdateTotalCost sets the "total_cost" field to the value that was provided on create.
func (u *RequestLogUpsertOne) UpdateTotalCost() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateTotalCost()
	})
}

// SetStream sets the "stream" field.
func (u *RequestLogUpsertOne) SetStream(v bool) *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetStream(v)
	})
}

// UpdateStream sets the "stream" field to the value that was provided on create.
func (u *RequestLogUpsertOne) UpdateStream() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateStream()
	})
}

// SetDurationMs sets the "duration_ms" field.
func (u *RequestLogUpsertOne) SetDurationMs(v int) *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetDurationMs(v)
	})
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *RequestLogUpsertOne) AddDurationMs(v int) *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.AddDurationMs(v)
	})
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *RequestLogUpsertOne) UpdateDurationMs() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateDurationMs()
	})
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (u *RequestLogUpsertOne) ClearDurationMs() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.ClearDurationMs()
	})
}

// SetFirstTokenMs sets the "first_token_ms" field.
func (u *RequestLogUpsertOne) SetFirstTokenMs(v int) *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetFirstTokenMs(v)
	})
}

// AddFirstTokenMs adds v to the "first_token_ms" field.
func (u *RequestLogUpsertOne) AddFirstTokenMs(v int) *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.AddFirstTokenMs(v)
	})
}

// UpdateFirstTokenMs sets the "first_token_ms" field to the value that was provided on create.
func (u *RequestLogUpsertOne) UpdateFirstTokenMs() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateFirstTokenMs()
	})
}

// ClearFirstTokenMs clears the value of the "first_token_ms" field.
func (u *RequestLogUpsertOne) ClearFirstTokenMs() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.ClearFirstTokenMs()
	})
}

// SetUserAgent sets the "user_agent" field.
func (u *RequestLogUpsertOne) SetUserAgent(v string) *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetUserAgent(v)
	})
}

// UpdateUserAgent sets the "user_agent" field to the value that was provided on create.
func (u *RequestLogUpsertOne) UpdateUserAgent() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateUserAgent()
	})
}

// ClearUserAgent clears the value of the "user_agent" field.
func (u *RequestLogUpsertOne) ClearUserAgent() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.ClearUserAgent()
	})
}

// SetIPAddress sets the "ip_address" field.
func (u *RequestLogUpsertOne) SetIPAddress(v string) *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetIPAddress(v)
	})
}

// UpdateIPAddress sets the "ip_address" field to the value that was provided on create.
func (u *RequestLogUpsertOne) UpdateIPAddress() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateIPAddress()
	})
}

// ClearIPAddress clears the value of the "ip_address" field.
func (u *RequestLogUpsertOne) ClearIPAddress() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.ClearIPAddress()
	})
}

// Exec executes the query.
func (u *RequestLogUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RequestLogCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RequestLogUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RequestLogUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RequestLogUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RequestLogCreateBulk is the builder for creating many RequestLog entities in bulk.
type RequestLogCreateBulk struct {
	config
	err      error
	builders []*RequestLogCreate
	conflict []sql.ConflictOption
}

// Save creates the RequestLog entities in the database.
func (_c *RequestLogCreateBulk) Save(ctx context.Context) ([]*RequestLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RequestLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RequestLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RequestLogCreateBulk) SaveX(ctx context.Context) []*RequestLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RequestLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RequestLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RequestLog.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RequestLogUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *RequestLogCreateBulk) OnConflict(opts ...sql.ConflictOption) *RequestLogUpsertBulk {
	_c.conflict = opts
	return &RequestLogUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RequestLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RequestLogCreateBulk) OnConflictColumns(columns ...string) *RequestLogUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RequestLogUpsertBulk{
		create: _c,
	}
}

// RequestLogUpsertBulk is the builder for "upsert"-ing
// a bulk of RequestLog nodes.
type RequestLogUpsertBulk struct {
	create *RequestLogCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RequestLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RequestLogUpsertBulk) UpdateNewValues() *RequestLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(requestlog.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RequestLog.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RequestLogUpsertBulk) Ignore() *RequestLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RequestLogUpsertBulk) DoNothing() *RequestLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RequestLogCreateBulk.OnConflict
// documentation for more info.
func (u *RequestLogUpsertBulk) Update(set func(*RequestLogUpsert)) *RequestLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RequestLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *RequestLogUpsertBulk) SetUserID(v int64) *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RequestLogUpsertBulk) UpdateUserID() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *RequestLogUpsertBulk) SetAPIKeyID(v int64) *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *RequestLogUpsertBulk) UpdateAPIKeyID() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetRequestID sets the "request_id" field.
func (u *RequestLogUpsertBulk) SetRequestID(v string) *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *RequestLogUpsertBulk) UpdateRequestID() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateRequestID()
	})
}

// ClearRequestID clears the value of the "request_id" field.
func (u *RequestLogUpsertBulk) ClearRequestID() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.ClearRequestID()
	})
}

// SetModel sets the "model" field.
func (u *RequestLogUpsertBulk) SetModel(v string) *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *RequestLogUpsertBulk) UpdateModel() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateModel()
	})
}

// SetInboundEndpoint sets the "inbound_endpoint" field.
func (u *RequestLogUpsertBulk) SetInboundEndpoint(v string) *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetInboundEndpoint(v)
	})
}

// UpdateInboundEndpoint sets the "inbound_endpoint" field to the value that was provided on create.
func (u *RequestLogUpsertBulk) UpdateInboundEndpoint() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateInboundEndpoint()
	})
}

// ClearInboundEndpoint clears the value of the "inbound_endpoint" field.
func (u *RequestLogUpsertBulk) ClearInboundEndpoint() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.ClearInboundEndpoint()
	})
}

// SetUpstreamEndpoint sets the "upstream_endpoint" field.
func (u *RequestLogUpsertBulk) SetUpstreamEndpoint(v string) *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetUpstreamEndpoint(v)
	})
}

// UpdateUpstreamEndpoint sets the "upstream_endpoint" field to the value that was provided on create.
func (u *RequestLogUpsertBulk) UpdateUpstreamEndpoint() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateUpstreamEndpoint()
	})
}

// ClearUpstreamEndpoint clears the value of the "upstream_endpoint" field.
func (u *RequestLogUpsertBulk) ClearUpstreamEndpoint() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.ClearUpstreamEndpoint()
	})
}

// SetMethod sets the "method" field.
func (u *RequestLogUpsertBulk) SetMethod(v string) *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetMethod(v)
	})
}

// UpdateMethod sets the "method" field to the value that was provided on create.
func (u *RequestLogUpsertBulk) UpdateMethod() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateMethod()
	})
}

// ClearMethod clears the value of the "method" field.
func (u *RequestLogUpsertBulk) ClearMethod() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.ClearMethod()
	})
}

// SetStatusCode sets the "status_code" field.
func (u *RequestLogUpsertBulk) SetStatusCode(v int) *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetStatusCode(v)
	})
}

// AddStatusCode adds v to the "status_code" field.
func (u *RequestLogUpsertBulk) AddStatusCode(v int) *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.AddStatusCode(v)
	})
}

// UpdateStatusCode sets the "status_code" field to the value that was provided on create.
func (u *RequestLogUpsertBulk) UpdateStatusCode() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateStatusCode()
	})
}

// ClearStatusCode clears the value of the "status_code" field.
func (u *RequestLogUpsertBulk) ClearStatusCode() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.ClearStatusCode()
	})
}

// SetErrorCode sets the "error_code" field.
func (u *RequestLogUpsertBulk) SetErrorCode(v string) *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetErrorCode(v)
	})
}

// UpdateErrorCode sets the "error_code" field to the value that was provided on create.
func (u *RequestLogUpsertBulk) UpdateErrorCode() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateErrorCode()
	})
}

// ClearErrorCode clears the value of the "error_code" field.
func (u *RequestLogUpsertBulk) ClearErrorCode() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.ClearErrorCode()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *RequestLogUpsertBulk) SetErrorMessage(v string) *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *RequestLogUpsertBulk) UpdateErrorMessage() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *RequestLogUpsertBulk) ClearErrorMessage() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.ClearErrorMessage()
	})
}

// SetInputTokens sets the "input_tokens" field.
func (u *RequestLogUpsertBulk) SetInputTokens(v int) *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetInputTokens(v)
	})
}

// AddInputTokens adds v to the "input_tokens" field.
func (u *RequestLogUpsertBulk) AddInputTokens(v int) *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.AddInputTokens(v)
	})
}

// UpdateInputTokens sets the "input_tokens" field to the value that was provided on create.
func (u *RequestLogUpsertBulk) UpdateInputTokens() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateInputTokens()
	})
}

// SetOutputTokens sets the "output_tokens" field.
func (u *RequestLogUpsertBulk) SetOutputTokens(v int) *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetOutputTokens(v)
	})
}

// AddOutputTokens adds v to the "output_tokens" field.
func (u *RequestLogUpsertBulk) AddOutputTokens(v int) *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.AddOutputTokens(v)
	})
}

// UpdateOutputTokens sets the "output_tokens" field to the value that was provided on create.
func (u *RequestLogUpsertBulk) UpdateOutputTokens() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateOutputTokens()
	})
}

// SetTotalCost sets the "total_cost" field.
func (u *RequestLogUpsertBulk) SetTotalCost(v float64) *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetTotalCost(v)
	})
}

// AddTotalCost adds v to the "total_cost" field.
func (u *RequestLogUpsertBulk) AddTotalCost(v float64) *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.AddTotalCost(v)
	})
}

// UpdateTotalCost sets the "total_cost" field to the value that was provided on create.
func (u *RequestLogUpsertBulk) UpdateTotalCost() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateTotalCost()
	})
}

// SetStream sets the "stream" field.
func (u *RequestLogUpsertBulk) SetStream(v bool) *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetStream(v)
	})
}

// UpdateStream sets the "stream" field to the value that was provided on create.
func (u *RequestLogUpsertBulk) UpdateStream() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateStream()
	})
}

// SetDurationMs sets the "duration_ms" field.
func (u *RequestLogUpsertBulk) SetDurationMs(v int) *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetDurationMs(v)
	})
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *RequestLogUpsertBulk) AddDurationMs(v int) *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.AddDurationMs(v)
	})
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *RequestLogUpsertBulk) UpdateDurationMs() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateDurationMs()
	})
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (u *RequestLogUpsertBulk) ClearDurationMs() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.ClearDurationMs()
	})
}

// SetFirstTokenMs sets the "first_token_ms" field.
func (u *RequestLogUpsertBulk) SetFirstTokenMs(v int) *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetFirstTokenMs(v)
	})
}

// AddFirstTokenMs adds v to the "first_token_ms" field.
func (u *RequestLogUpsertBulk) AddFirstTokenMs(v int) *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.AddFirstTokenMs(v)
	})
}

// UpdateFirstTokenMs sets the "first_token_ms" field to the value that was provided on create.
func (u *RequestLogUpsertBulk) UpdateFirstTokenMs() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateFirstTokenMs()
	})
}

// ClearFirstTokenMs clears the value of the "first_token_ms" field.
func (u *RequestLogUpsertBulk) ClearFirstTokenMs() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.ClearFirstTokenMs()
	})
}

// SetUserAgent sets the "user_agent" field.
func (u *RequestLogUpsertBulk) SetUserAgent(v string) *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetUserAgent(v)
	})
}

// UpdateUserAgent sets the "user_agent" field to the value that was provided on create.
func (u *RequestLogUpsertBulk) UpdateUserAgent() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateUserAgent()
	})
}

// ClearUserAgent clears the value of the "user_agent" field.
func (u *RequestLogUpsertBulk) ClearUserAgent() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.ClearUserAgent()
	})
}

// SetIPAddress sets the "ip_address" field.
func (u *RequestLogUpsertBulk) SetIPAddress(v string) *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetIPAddress(v)
	})
}

// UpdateIPAddress sets the "ip_address" field to the value that was provided on create.
func (u *RequestLogUpsertBulk) UpdateIPAddress() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateIPAddress()
	})
}

// ClearIPAddress clears the value of the "ip_address" field.
func (u *RequestLogUpsertBulk) ClearIPAddress() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.ClearIPAddress()
	})
}

// Exec executes the query.
func (u *RequestLogUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RequestLogCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RequestLogCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RequestLogUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
