// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/requestlog"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// RequestLogUpdate is the builder for updating RequestLog entities.
type RequestLogUpdate struct {
	config
	hooks    []Hook
	mutation *RequestLogMutation
}

// Where appends a list predicates to the RequestLogUpdate builder.
func (_u *RequestLogUpdate) Where(ps ...predicate.RequestLog) *RequestLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *RequestLogUpdate) SetUserID(v int64) *RequestLogUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableUserID(v *int64) *RequestLogUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *RequestLogUpdate) SetAPIKeyID(v int64) *RequestLogUpdate {
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableAPIKeyID(v *int64) *RequestLogUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *RequestLogUpdate) SetRequestID(v string) *RequestLogUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableRequestID(v *string) *RequestLogUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// ClearRequestID clears the value of the "request_id" field.
func (_u *RequestLogUpdate) ClearRequestID() *RequestLogUpdate {
	_u.mutation.ClearRequestID()
	return _u
}

// SetModel sets the "model" field.
func (_u *RequestLogUpdate) SetModel(v string) *RequestLogUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableModel(v *string) *RequestLogUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetInboundEndpoint sets the "inbound_endpoint" field.
func (_u *RequestLogUpdate) SetInboundEndpoint(v string) *RequestLogUpdate {
	_u.mutation.SetInboundEndpoint(v)
	return _u
}

// SetNillableInboundEndpoint sets the "inbound_endpoint" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableInboundEndpoint(v *string) *RequestLogUpdate {
	if v != nil {
		_u.SetInboundEndpoint(*v)
	}
	return _u
}

// ClearInboundEndpoint clears the value of the "inbound_endpoint" field.
func (_u *RequestLogUpdate) ClearInboundEndpoint() *RequestLogUpdate {
	_u.mutation.ClearInboundEndpoint()
	return _u
}

// SetUpstreamEndpoint sets the "upstream_endpoint" field.
func (_u *RequestLogUpdate) SetUpstreamEndpoint(v string) *RequestLogUpdate {
	_u.mutation.SetUpstreamEndpoint(v)
	return _u
}

// SetNillableUpstreamEndpoint sets the "upstream_endpoint" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableUpstreamEndpoint(v *string) *RequestLogUpdate {
	if v != nil {
		_u.SetUpstreamEndpoint(*v)
	}
	return _u
}

// ClearUpstreamEndpoint clears the value of the "upstream_endpoint" field.
func (_u *RequestLogUpdate) ClearUpstreamEndpoint() *RequestLogUpdate {
	_u.mutation.ClearUpstreamEndpoint()
	return _u
}

// SetMethod sets the "method" field.
func (_u *RequestLogUpdate) SetMethod(v string) *RequestLogUpdate {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableMethod(v *string) *RequestLogUpdate {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// ClearMethod clears the value of the "method" field.
func (_u *RequestLogUpdate) ClearMethod() *RequestLogUpdate {
	_u.mutation.ClearMethod()
	return _u
}

// SetStatusCode sets the "status_code" field.
func (_u *RequestLogUpdate) SetStatusCode(v int) *RequestLogUpdate {
	_u.mutation.ResetStatusCode()
	_u.mutation.SetStatusCode(v)
	return _u
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableStatusCode(v *int) *RequestLogUpdate {
	if v != nil {
		_u.SetStatusCode(*v)
	}
	return _u
}

// AddStatusCode adds value to the "status_code" field.
func (_u *RequestLogUpdate) AddStatusCode(v int) *RequestLogUpdate {
	_u.mutation.AddStatusCode(v)
	return _u
}

// ClearStatusCode clears the value of the "status_code" field.
func (_u *RequestLogUpdate) ClearStatusCode() *RequestLogUpdate {
	_u.mutation.ClearStatusCode()
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *RequestLogUpdate) SetErrorCode(v string) *RequestLogUpdate {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableErrorCode(v *string) *RequestLogUpdate {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// ClearErrorCode clears the value of the "error_code" field.
func (_u *RequestLogUpdate) ClearErrorCode() *RequestLogUpdate {
	_u.mutation.ClearErrorCode()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *RequestLogUpdate) SetErrorMessage(v string) *RequestLogUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableErrorMessage(v *string) *RequestLogUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *RequestLogUpdate) ClearErrorMessage() *RequestLogUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetInputTokens sets the "input_tokens" field.
func (_u *RequestLogUpdate) SetInputTokens(v int) *RequestLogUpdate {
	_u.mutation.ResetInputTokens()
	_u.mutation.SetInputTokens(v)
	return _u
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableInputTokens(v *int) *RequestLogUpdate {
	if v != nil {
		_u.SetInputTokens(*v)
	}
	return _u
}

// AddInputTokens adds value to the "input_tokens" field.
func (_u *RequestLogUpdate) AddInputTokens(v int) *RequestLogUpdate {
	_u.mutation.AddInputTokens(v)
	return _u
}

// SetOutputTokens sets the "output_tokens" field.
func (_u *RequestLogUpdate) SetOutputTokens(v int) *RequestLogUpdate {
	_u.mutation.ResetOutputTokens()
	_u.mutation.SetOutputTokens(v)
	return _u
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableOutputTokens(v *int) *RequestLogUpdate {
	if v != nil {
		_u.SetOutputTokens(*v)
	}
	return _u
}

// AddOutputTokens adds value to the "output_tokens" field.
func (_u *RequestLogUpdate) AddOutputTokens(v int) *RequestLogUpdate {
	_u.mutation.AddOutputTokens(v)
	return _u
}

// SetTotalCost sets the "total_cost" field.
func (_u *RequestLogUpdate) SetTotalCost(v float64) *RequestLogUpdate {
	_u.mutation.ResetTotalCost()
	_u.mutation.SetTotalCost(v)
	return _u
}

// SetNillableTotalCost sets the "total_cost" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableTotalCost(v *float64) *RequestLogUpdate {
	if v != nil {
		_u.SetTotalCost(*v)
	}
	return _u
}

// AddTotalCost adds value to the "total_cost" field.
func (_u *RequestLogUpdate) AddTotalCost(v float64) *RequestLogUpdate {
	_u.mutation.AddTotalCost(v)
	return _u
}

// SetStream sets the "stream" field.
func (_u *RequestLogUpdate) SetStream(v bool) *RequestLogUpdate {
	_u.mutation.SetStream(v)
	return _u
}

// SetNillableStream sets the "stream" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableStream(v *bool) *RequestLogUpdate {
	if v != nil {
		_u.SetStream(*v)
	}
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *RequestLogUpdate) SetDurationMs(v int) *RequestLogUpdate {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableDurationMs(v *int) *RequestLogUpdate {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *RequestLogUpdate) AddDurationMs(v int) *RequestLogUpdate {
	_u.mutation.AddDurationMs(v)
	return _u
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (_u *RequestLogUpdate) ClearDurationMs() *RequestLogUpdate {
	_u.mutation.ClearDurationMs()
	return _u
}

// SetFirstTokenMs sets the "first_token_ms" field.
func (_u *RequestLogUpdate) SetFirstTokenMs(v int) *RequestLogUpdate {
	_u.mutation.ResetFirstTokenMs()
	_u.mutation.SetFirstTokenMs(v)
	return _u
}

// SetNillableFirstTokenMs sets the "first_token_ms" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableFirstTokenMs(v *int) *RequestLogUpdate {
	if v != nil {
		_u.SetFirstTokenMs(*v)
	}
	return _u
}

// AddFirstTokenMs adds value to the "first_token_ms" field.
func (_u *RequestLogUpdate) AddFirstTokenMs(v int) *RequestLogUpdate {
	_u.mutation.AddFirstTokenMs(v)
	return _u
}

// ClearFirstTokenMs clears the value of the "first_token_ms" field.
func (_u *RequestLogUpdate) ClearFirstTokenMs() *RequestLogUpdate {
	_u.mutation.ClearFirstTokenMs()
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *RequestLogUpdate) SetUserAgent(v string) *RequestLogUpdate {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableUserAgent(v *string) *RequestLogUpdate {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *RequestLogUpdate) ClearUserAgent() *RequestLogUpdate {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetIPAddress sets the "ip_address" field.
func (_u *RequestLogUpdate) SetIPAddress(v string) *RequestLogUpdate {
	_u.mutation.SetIPAddress(v)
	return _u
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableIPAddress(v *string) *RequestLogUpdate {
	if v != nil {
		_u.SetIPAddress(*v)
	}
	return _u
}

// ClearIPAddress clears the value of the "ip_address" field.
func (_u *RequestLogUpdate) ClearIPAddress() *RequestLogUpdate {
	_u.mutation.ClearIPAddress()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *RequestLogUpdate) SetUser(v *User) *RequestLogUpdate {
	return _u.SetUserID(v.ID)
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_u *RequestLogUpdate) SetAPIKey(v *APIKey) *RequestLogUpdate {
	return _u.SetAPIKeyID(v.ID)
}

// Mutation returns the RequestLogMutation object of the builder.
func (_u *RequestLogUpdate) Mutation() *RequestLogMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *RequestLogUpdate) ClearUser() *RequestLogUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearAPIKey clears the "api_key" edge to the APIKey entity.
func (_u *RequestLogUpdate) ClearAPIKey() *RequestLogUpdate {
	_u.mutation.ClearAPIKey()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RequestLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RequestLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RequestLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RequestLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RequestLogUpdate) check() error {
	if v, ok := _u.mutation.RequestID(); ok {
		if err := requestlog.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "RequestLog.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := requestlog.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "RequestLog.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InboundEndpoint(); ok {
		if err := requestlog.InboundEndpointValidator(v); err != nil {
			return &ValidationError{Name: "inbound_endpoint", err: fmt.Errorf(`ent: validator failed for field "RequestLog.inbound_endpoint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamEndpoint(); ok {
		if err := requestlog.UpstreamEndpointValidator(v); err != nil {
			return &ValidationError{Name: "upstream_endpoint", err: fmt.Errorf(`ent: validator failed for field "RequestLog.upstream_endpoint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Method(); ok {
		if err := requestlog.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "RequestLog.method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorCode(); ok {
		if err := requestlog.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "RequestLog.error_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserAgent(); ok {
		if err := requestlog.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "RequestLog.user_agent": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IPAddress(); ok {
		if err := requestlog.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf(`ent: validator failed for field "RequestLog.ip_address": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RequestLog.user"`)
	}
	if _u.mutation.APIKeyCleared() && len(_u.mutation.APIKeyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RequestLog.api_key"`)
	}
	return nil
}

func (_u *RequestLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(requestlog.Table, requestlog.Columns, sqlgraph.NewFieldSpec(requestlog.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(requestlog.FieldRequestID, field.TypeString, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(requestlog.FieldRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(requestlog.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.InboundEndpoint(); ok {
		_spec.SetField(requestlog.FieldInboundEndpoint, field.TypeString, value)
	}
	if _u.mutation.InboundEndpointCleared() {
		_spec.ClearField(requestlog.FieldInboundEndpoint, field.TypeString)
	}
	if value, ok := _u.mutation.UpstreamEndpoint(); ok {
		_spec.SetField(requestlog.FieldUpstreamEndpoint, field.TypeString, value)
	}
	if _u.mutation.UpstreamEndpointCleared() {
		_spec.ClearField(requestlog.FieldUpstreamEndpoint, field.TypeString)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(requestlog.FieldMethod, field.TypeString, value)
	}
	if _u.mutation.MethodCleared() {
		_spec.ClearField(requestlog.FieldMethod, field.TypeString)
	}
	if value, ok := _u.mutation.StatusCode(); ok {
		_spec.SetField(requestlog.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatusCode(); ok {
		_spec.AddField(requestlog.FieldStatusCode, field.TypeInt, value)
	}
	if _u.mutation.StatusCodeCleared() {
		_spec.ClearField(requestlog.FieldStatusCode, field.TypeInt)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(requestlog.FieldErrorCode, field.TypeString, value)
	}
	if _u.mutation.ErrorCodeCleared() {
		_spec.ClearField(requestlog.FieldErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(requestlog.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(requestlog.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.InputTokens(); ok {
		_spec.SetField(requestlog.FieldInputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedInputTokens(); ok {
		_spec.AddField(requestlog.FieldInputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.OutputTokens(); ok {
		_spec.SetField(requestlog.FieldOutputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOutputTokens(); ok {
		_spec.AddField(requestlog.FieldOutputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalCost(); ok {
		_spec.SetField(requestlog.FieldTotalCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalCost(); ok {
		_spec.AddField(requestlog.FieldTotalCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Stream(); ok {
		_spec.SetField(requestlog.FieldStream, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(requestlog.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(requestlog.FieldDurationMs, field.TypeInt, value)
	}
	if _u.mutation.DurationMsCleared() {
		_spec.ClearField(requestlog.FieldDurationMs, field.TypeInt)
	}
	if value, ok := _u.mutation.FirstTokenMs(); ok {
		_spec.SetField(requestlog.FieldFirstTokenMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFirstTokenMs(); ok {
		_spec.AddField(requestlog.FieldFirstTokenMs, field.TypeInt, value)
	}
	if _u.mutation.FirstTokenMsCleared() {
		_spec.ClearField(requestlog.FieldFirstTokenMs, field.TypeInt)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(requestlog.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(requestlog.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.IPAddress(); ok {
		_spec.SetField(requestlog.FieldIPAddress, field.TypeString, value)
	}
	if _u.mutation.IPAddressCleared() {
		_spec.ClearField(requestlog.FieldIPAddress, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   requestlog.UserTable,
			Columns: []string{requestlog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   requestlog.UserTable,
			Columns: []string{requestlog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APIKeyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   requestlog.APIKeyTable,
			Columns: []string{requestlog.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   requestlog.APIKeyTable,
			Columns: []string{requestlog.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{requestlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RequestLogUpdateOne is the builder for updating a single RequestLog entity.
type RequestLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RequestLogMutation
}

// SetUserID sets the "user_id" field.
func (_u *RequestLogUpdateOne) SetUserID(v int64) *RequestLogUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableUserID(v *int64) *RequestLogUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *RequestLogUpdateOne) SetAPIKeyID(v int64) *RequestLogUpdateOne {
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableAPIKeyID(v *int64) *RequestLogUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *RequestLogUpdateOne) SetRequestID(v string) *RequestLogUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableRequestID(v *string) *RequestLogUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// ClearRequestID clears the value of the "request_id" field.
func (_u *RequestLogUpdateOne) ClearRequestID() *RequestLogUpdateOne {
	_u.mutation.ClearRequestID()
	return _u
}

// SetModel sets the "model" field.
func (_u *RequestLogUpdateOne) SetModel(v string) *RequestLogUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableModel(v *string) *RequestLogUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetInboundEndpoint sets the "inbound_endpoint" field.
func (_u *RequestLogUpdateOne) SetInboundEndpoint(v string) *RequestLogUpdateOne {
	_u.mutation.SetInboundEndpoint(v)
	return _u
}

// SetNillableInboundEndpoint sets the "inbound_endpoint" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableInboundEndpoint(v *string) *RequestLogUpdateOne {
	if v != nil {
		_u.SetInboundEndpoint(*v)
	}
	return _u
}

// ClearInboundEndpoint clears the value of the "inbound_endpoint" field.
func (_u *RequestLogUpdateOne) ClearInboundEndpoint() *RequestLogUpdateOne {
	_u.mutation.ClearInboundEndpoint()
	return _u
}

// SetUpstreamEndpoint sets the "upstream_endpoint" field.
func (_u *RequestLogUpdateOne) SetUpstreamEndpoint(v string) *RequestLogUpdateOne {
	_u.mutation.SetUpstreamEndpoint(v)
	return _u
}

// SetNillableUpstreamEndpoint sets the "upstream_endpoint" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableUpstreamEndpoint(v *string) *RequestLogUpdateOne {
	if v != nil {
		_u.SetUpstreamEndpoint(*v)
	}
	return _u
}

// ClearUpstreamEndpoint clears the value of the "upstream_endpoint" field.
func (_u *RequestLogUpdateOne) ClearUpstreamEndpoint() *RequestLogUpdateOne {
	_u.mutation.ClearUpstreamEndpoint()
	return _u
}

// SetMethod sets the "method" field.
func (_u *RequestLogUpdateOne) SetMethod(v string) *RequestLogUpdateOne {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableMethod(v *string) *RequestLogUpdateOne {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// ClearMethod clears the value of the "method" field.
func (_u *RequestLogUpdateOne) ClearMethod() *RequestLogUpdateOne {
	_u.mutation.ClearMethod()
	return _u
}

// SetStatusCode sets the "status_code" field.
func (_u *RequestLogUpdateOne) SetStatusCode(v int) *RequestLogUpdateOne {
	_u.mutation.ResetStatusCode()
	_u.mutation.SetStatusCode(v)
	return _u
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableStatusCode(v *int) *RequestLogUpdateOne {
	if v != nil {
		_u.SetStatusCode(*v)
	}
	return _u
}

// AddStatusCode adds value to the "status_code" field.
func (_u *RequestLogUpdateOne) AddStatusCode(v int) *RequestLogUpdateOne {
	_u.mutation.AddStatusCode(v)
	return _u
}

// ClearStatusCode clears the value of the "status_code" field.
func (_u *RequestLogUpdateOne) ClearStatusCode() *RequestLogUpdateOne {
	_u.mutation.ClearStatusCode()
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *RequestLogUpdateOne) SetErrorCode(v string) *RequestLogUpdateOne {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableErrorCode(v *string) *RequestLogUpdateOne {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// ClearErrorCode clears the value of the "error_code" field.
func (_u *RequestLogUpdateOne) ClearErrorCode() *RequestLogUpdateOne {
	_u.mutation.ClearErrorCode()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *RequestLogUpdateOne) SetErrorMessage(v string) *RequestLogUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableErrorMessage(v *string) *RequestLogUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *RequestLogUpdateOne) ClearErrorMessage() *RequestLogUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetInputTokens sets the "input_tokens" field.
func (_u *RequestLogUpdateOne) SetInputTokens(v int) *RequestLogUpdateOne {
	_u.mutation.ResetInputTokens()
	_u.mutation.SetInputTokens(v)
	return _u
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableInputTokens(v *int) *RequestLogUpdateOne {
	if v != nil {
		_u.SetInputTokens(*v)
	}
	return _u
}

// AddInputTokens adds value to the "input_tokens" field.
func (_u *RequestLogUpdateOne) AddInputTokens(v int) *RequestLogUpdateOne {
	_u.mutation.AddInputTokens(v)
	return _u
}

// SetOutputTokens sets the "output_tokens" field.
func (_u *RequestLogUpdateOne) SetOutputTokens(v int) *RequestLogUpdateOne {
	_u.mutation.ResetOutputTokens()
	_u.mutation.SetOutputTokens(v)
	return _u
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableOutputTokens(v *int) *RequestLogUpdateOne {
	if v != nil {
		_u.SetOutputTokens(*v)
	}
	return _u
}

// AddOutputTokens adds value to the "output_tokens" field.
func (_u *RequestLogUpdateOne) AddOutputTokens(v int) *RequestLogUpdateOne {
	_u.mutation.AddOutputTokens(v)
	return _u
}

// SetTotalCost sets the "total_cost" field.
func (_u *RequestLogUpdateOne) SetTotalCost(v float64) *RequestLogUpdateOne {
	_u.mutation.ResetTotalCost()
	_u.mutation.SetTotalCost(v)
	return _u
}

// SetNillableTotalCost sets the "total_cost" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableTotalCost(v *float64) *RequestLogUpdateOne {
	if v != nil {
		_u.SetTotalCost(*v)
	}
	return _u
}

// AddTotalCost adds value to the "total_cost" field.
func (_u *RequestLogUpdateOne) AddTotalCost(v float64) *RequestLogUpdateOne {
	_u.mutation.AddTotalCost(v)
	return _u
}

// SetStream sets the "stream" field.
func (_u *RequestLogUpdateOne) SetStream(v bool) *RequestLogUpdateOne {
	_u.mutation.SetStream(v)
	return _u
}

// SetNillableStream sets the "stream" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableStream(v *bool) *RequestLogUpdateOne {
	if v != nil {
		_u.SetStream(*v)
	}
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *RequestLogUpdateOne) SetDurationMs(v int) *RequestLogUpdateOne {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableDurationMs(v *int) *RequestLogUpdateOne {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *RequestLogUpdateOne) AddDurationMs(v int) *RequestLogUpdateOne {
	_u.mutation.AddDurationMs(v)
	return _u
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (_u *RequestLogUpdateOne) ClearDurationMs() *RequestLogUpdateOne {
	_u.mutation.ClearDurationMs()
	return _u
}

// SetFirstTokenMs sets the "first_token_ms" field.
func (_u *RequestLogUpdateOne) SetFirstTokenMs(v int) *RequestLogUpdateOne {
	_u.mutation.ResetFirstTokenMs()
	_u.mutation.SetFirstTokenMs(v)
	return _u
}

// SetNillableFirstTokenMs sets the "first_token_ms" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableFirstTokenMs(v *int) *RequestLogUpdateOne {
	if v != nil {
		_u.SetFirstTokenMs(*v)
	}
	return _u
}

// AddFirstTokenMs adds value to the "first_token_ms" field.
func (_u *RequestLogUpdateOne) AddFirstTokenMs(v int) *RequestLogUpdateOne {
	_u.mutation.AddFirstTokenMs(v)
	return _u
}

// ClearFirstTokenMs clears the value of the "first_token_ms" field.
func (_u *RequestLogUpdateOne) ClearFirstTokenMs() *RequestLogUpdateOne {
	_u.mutation.ClearFirstTokenMs()
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *RequestLogUpdateOne) SetUserAgent(v string) *RequestLogUpdateOne {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableUserAgent(v *string) *RequestLogUpdateOne {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *RequestLogUpdateOne) ClearUserAgent() *RequestLogUpdateOne {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetIPAddress sets the "ip_address" field.
func (_u *RequestLogUpdateOne) SetIPAddress(v string) *RequestLogUpdateOne {
	_u.mutation.SetIPAddress(v)
	return _u
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableIPAddress(v *string) *RequestLogUpdateOne {
	if v != nil {
		_u.SetIPAddress(*v)
	}
	return _u
}

// ClearIPAddress clears the value of the "ip_address" field.
func (_u *RequestLogUpdateOne) ClearIPAddress() *RequestLogUpdateOne {
	_u.mutation.ClearIPAddress()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *RequestLogUpdateOne) SetUser(v *User) *RequestLogUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_u *RequestLogUpdateOne) SetAPIKey(v *APIKey) *RequestLogUpdateOne {
	return _u.SetAPIKeyID(v.ID)
}

// Mutation returns the RequestLogMutation object of the builder.
func (_u *RequestLogUpdateOne) Mutation() *RequestLogMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *RequestLogUpdateOne) ClearUser() *RequestLogUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearAPIKey clears the "api_key" edge to the APIKey entity.
func (_u *RequestLogUpdateOne) ClearAPIKey() *RequestLogUpdateOne {
	_u.mutation.ClearAPIKey()
	return _u
}

// Where appends a list predicates to the RequestLogUpdate builder.
func (_u *RequestLogUpdateOne) Where(ps ...predicate.RequestLog) *RequestLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RequestLogUpdateOne) Select(field string, fields ...string) *RequestLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RequestLog entity.
func (_u *RequestLogUpdateOne) Save(ctx context.Context) (*RequestLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RequestLogUpdateOne) SaveX(ctx context.Context) *RequestLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RequestLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RequestLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RequestLogUpdateOne) check() error {
	if v, ok := _u.mutation.RequestID(); ok {
		if err := requestlog.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "RequestLog.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := requestlog.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "RequestLog.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InboundEndpoint(); ok {
		if err := requestlog.InboundEndpointValidator(v); err != nil {
			return &ValidationError{Name: "inbound_endpoint", err: fmt.Errorf(`ent: validator failed for field "RequestLog.inbound_endpoint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamEndpoint(); ok {
		if err := requestlog.UpstreamEndpointValidator(v); err != nil {
			return &ValidationError{Name: "upstream_endpoint", err: fmt.Errorf(`ent: validator failed for field "RequestLog.upstream_endpoint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Method(); ok {
		if err := requestlog.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "RequestLog.method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorCode(); ok {
		if err := requestlog.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "RequestLog.error_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserAgent(); ok {
		if err := requestlog.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "RequestLog.user_agent": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IPAddress(); ok {
		if err := requestlog.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf(`ent: validator failed for field "RequestLog.ip_address": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RequestLog.user"`)
	}
	if _u.mutation.APIKeyCleared() && len(_u.mutation.APIKeyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RequestLog.api_key"`)
	}
	return nil
}

func (_u *RequestLogUpdateOne) sqlSave(ctx context.Context) (_node *RequestLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(requestlog.Table, requestlog.Columns, sqlgraph.NewFieldSpec(requestlog.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RequestLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, requestlog.FieldID)
		for _, f := range fields {
			if !requestlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != requestlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(requestlog.FieldRequestID, field.TypeString, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(requestlog.FieldRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(requestlog.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.InboundEndpoint(); ok {
		_spec.SetField(requestlog.FieldInboundEndpoint, field.TypeString, value)
	}
	if _u.mutation.InboundEndpointCleared() {
		_spec.ClearField(requestlog.FieldInboundEndpoint, field.TypeString)
	}
	if value, ok := _u.mutation.UpstreamEndpoint(); ok {
		_spec.SetField(requestlog.FieldUpstreamEndpoint, field.TypeString, value)
	}
	if _u.mutation.UpstreamEndpointCleared() {
		_spec.ClearField(requestlog.FieldUpstreamEndpoint, field.TypeString)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(requestlog.FieldMethod, field.TypeString, value)
	}
	if _u.mutation.MethodCleared() {
		_spec.ClearField(requestlog.FieldMethod, field.TypeString)
	}
	if value, ok := _u.mutation.StatusCode(); ok {
		_spec.SetField(requestlog.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatusCode(); ok {
		_spec.AddField(requestlog.FieldStatusCode, field.TypeInt, value)
	}
	if _u.mutation.StatusCodeCleared() {
		_spec.ClearField(requestlog.FieldStatusCode, field.TypeInt)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(requestlog.FieldErrorCode, field.TypeString, value)
	}
	if _u.mutation.ErrorCodeCleared() {
		_spec.ClearField(requestlog.FieldErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(requestlog.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(requestlog.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.InputTokens(); ok {
		_spec.SetField(requestlog.FieldInputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedInputTokens(); ok {
		_spec.AddField(requestlog.FieldInputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.OutputTokens(); ok {
		_spec.SetField(requestlog.FieldOutputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOutputTokens(); ok {
		_spec.AddField(requestlog.FieldOutputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalCost(); ok {
		_spec.SetField(requestlog.FieldTotalCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalCost(); ok {
		_spec.AddField(requestlog.FieldTotalCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Stream(); ok {
		_spec.SetField(requestlog.FieldStream, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(requestlog.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(requestlog.FieldDurationMs, field.TypeInt, value)
	}
	if _u.mutation.DurationMsCleared() {
		_spec.ClearField(requestlog.FieldDurationMs, field.TypeInt)
	}
	if value, ok := _u.mutation.FirstTokenMs(); ok {
		_spec.SetField(requestlog.FieldFirstTokenMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFirstTokenMs(); ok {
		_spec.AddField(requestlog.FieldFirstTokenMs, field.TypeInt, value)
	}
	if _u.mutation.FirstTokenMsCleared() {
		_spec.ClearField(requestlog.FieldFirstTokenMs, field.TypeInt)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(requestlog.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(requestlog.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.IPAddress(); ok {
		_spec.SetField(requestlog.FieldIPAddress, field.TypeString, value)
	}
	if _u.mutation.IPAddressCleared() {
		_spec.ClearField(requestlog.FieldIPAddress, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   requestlog.UserTable,
			Columns: []string{requestlog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   requestlog.UserTable,
			Columns: []string{requestlog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APIKeyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   requestlog.APIKeyTable,
			Columns: []string{requestlog.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   requestlog.APIKeyTable,
			Columns: []string{requestlog.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RequestLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{requestlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
