// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/requestlog"
	"github.com/Wei-Shaw/sub2api/ent/requestlogpayload"
)

// RequestLogPayload is the model entity for the RequestLogPayload schema.
type RequestLogPayload struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// RequestLogID holds the value of the "request_log_id" field.
	RequestLogID int64 `json:"request_log_id,omitempty"`
	// RequestBody holds the value of the "request_body" field.
	RequestBody []byte `json:"request_body,omitempty"`
	// RequestBodyEncoding holds the value of the "request_body_encoding" field.
	RequestBodyEncoding *string `json:"request_body_encoding,omitempty"`
	// RequestBodyBytes holds the value of the "request_body_bytes" field.
	RequestBodyBytes *int `json:"request_body_bytes,omitempty"`
	// RequestBodyTruncated holds the value of the "request_body_truncated" field.
	RequestBodyTruncated bool `json:"request_body_truncated,omitempty"`
	// ResponseBody holds the value of the "response_body" field.
	ResponseBody []byte `json:"response_body,omitempty"`
	// ResponseBodyEncoding holds the value of the "response_body_encoding" field.
	ResponseBodyEncoding *string `json:"response_body_encoding,omitempty"`
	// ResponseBodyBytes holds the value of the "response_body_bytes" field.
	ResponseBodyBytes *int `json:"response_body_bytes,omitempty"`
	// ResponseBodyTruncated holds the value of the "response_body_truncated" field.
	ResponseBodyTruncated bool `json:"response_body_truncated,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RequestLogPayloadQuery when eager-loading is set.
	Edges        RequestLogPayloadEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RequestLogPayloadEdges holds the relations/edges for other nodes in the graph.
type RequestLogPayloadEdges struct {
	// RequestLog holds the value of the request_log edge.
	RequestLog *RequestLog `json:"request_log,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// RequestLogOrErr returns the RequestLog value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RequestLogPayloadEdges) RequestLogOrErr() (*RequestLog, error) {
	if e.RequestLog != nil {
		return e.RequestLog, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: requestlog.Label}
	}
	return nil, &NotLoadedError{edge: "request_log"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RequestLogPayload) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case requestlogpayload.FieldRequestBody, requestlogpayload.FieldResponseBody:
			values[i] = new([]byte)
		case requestlogpayload.FieldRequestBodyTruncated, requestlogpayload.FieldResponseBodyTruncated:
			values[i] = new(sql.NullBool)
		case requestlogpayload.FieldID, requestlogpayload.FieldRequestLogID, requestlogpayload.FieldRequestBodyBytes, requestlogpayload.FieldResponseBodyBytes:
			values[i] = new(sql.NullInt64)
		case requestlogpayload.FieldRequestBodyEncoding, requestlogpayload.FieldResponseBodyEncoding:
			values[i] = new(sql.NullString)
		case requestlogpayload.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RequestLogPayload fields.
func (_m *RequestLogPayload) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case requestlogpayload.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case requestlogpayload.FieldRequestLogID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field request_log_id", values[i])
			} else if value.Valid {
				_m.RequestLogID = value.Int64
			}
		case requestlogpayload.FieldRequestBody:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field request_body", values[i])
			} else if value != nil {
				_m.RequestBody = *value
			}
		case requestlogpayload.FieldRequestBodyEncoding:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_body_encoding", values[i])
			} else if value.Valid {
				_m.RequestBodyEncoding = new(string)
				*_m.RequestBodyEncoding = value.String
			}
		case requestlogpayload.FieldRequestBodyBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field request_body_bytes", values[i])
			} else if value.Valid {
				_m.RequestBodyBytes = new(int)
				*_m.RequestBodyBytes = int(value.Int64)
			}
		case requestlogpayload.FieldRequestBodyTruncated:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field request_body_truncated", values[i])
			} else if value.Valid {
				_m.RequestBodyTruncated = value.Bool
			}
		case requestlogpayload.FieldResponseBody:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field response_body", values[i])
			} else if value != nil {
				_m.ResponseBody = *value
			}
		case requestlogpayload.FieldResponseBodyEncoding:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field response_body_encoding", values[i])
			} else if value.Valid {
				_m.ResponseBodyEncoding = new(string)
				*_m.ResponseBodyEncoding = value.String
			}
		case requestlogpayload.FieldResponseBodyBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field response_body_bytes", values[i])
			} else if value.Valid {
				_m.ResponseBodyBytes = new(int)
				*_m.ResponseBodyBytes = int(value.Int64)
			}
		case requestlogpayload.FieldResponseBodyTruncated:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field response_body_truncated", values[i])
			} else if value.Valid {
				_m.ResponseBodyTruncated = value.Bool
			}
		case requestlogpayload.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RequestLogPayload.
// This includes values selected through modifiers, order, etc.
func (_m *RequestLogPayload) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRequestLog queries the "request_log" edge of the RequestLogPayload entity.
func (_m *RequestLogPayload) QueryRequestLog() *RequestLogQuery {
	return NewRequestLogPayloadClient(_m.config).QueryRequestLog(_m)
}

// Update returns a builder for updating this RequestLogPayload.
// Note that you need to call RequestLogPayload.Unwrap() before calling this method if this RequestLogPayload
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RequestLogPayload) Update() *RequestLogPayloadUpdateOne {
	return NewRequestLogPayloadClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RequestLogPayload entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RequestLogPayload) Unwrap() *RequestLogPayload {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RequestLogPayload is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RequestLogPayload) String() string {
	var builder strings.Builder
	builder.WriteString("RequestLogPayload(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("request_log_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestLogID))
	builder.WriteString(", ")
	builder.WriteString("request_body=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestBody))
	builder.WriteString(", ")
	if v := _m.RequestBodyEncoding; v != nil {
		builder.WriteString("request_body_encoding=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.RequestBodyBytes; v != nil {
		builder.WriteString("request_body_bytes=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("request_body_truncated=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestBodyTruncated))
	builder.WriteString(", ")
	builder.WriteString("response_body=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResponseBody))
	builder.WriteString(", ")
	if v := _m.ResponseBodyEncoding; v != nil {
		builder.WriteString("response_body_encoding=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ResponseBodyBytes; v != nil {
		builder.WriteString("response_body_bytes=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("response_body_truncated=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResponseBodyTruncated))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RequestLogPayloads is a parsable slice of RequestLogPayload.
type RequestLogPayloads []*RequestLogPayload
