// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/requestlog"
	"github.com/Wei-Shaw/sub2api/ent/requestlogpayload"
)

// RequestLogPayloadCreate is the builder for creating a RequestLogPayload entity.
type RequestLogPayloadCreate struct {
	config
	mutation *RequestLogPayloadMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetRequestLogID sets the "request_log_id" field.
func (_c *RequestLogPayloadCreate) SetRequestLogID(v int64) *RequestLogPayloadCreate {
	_c.mutation.SetRequestLogID(v)
	return _c
}

// SetRequestBody sets the "request_body" field.
func (_c *RequestLogPayloadCreate) SetRequestBody(v []byte) *RequestLogPayloadCreate {
	_c.mutation.SetRequestBody(v)
	return _c
}

// SetRequestBodyEncoding sets the "request_body_encoding" field.
func (_c *RequestLogPayloadCreate) SetRequestBodyEncoding(v string) *RequestLogPayloadCreate {
	_c.mutation.SetRequestBodyEncoding(v)
	return _c
}

// SetNillableRequestBodyEncoding sets the "request_body_encoding" field if the given value is not nil.
func (_c *RequestLogPayloadCreate) SetNillableRequestBodyEncoding(v *string) *RequestLogPayloadCreate {
	if v != nil {
		_c.SetRequestBodyEncoding(*v)
	}
	return _c
}

// SetRequestBodyBytes sets the "request_body_bytes" field.
func (_c *RequestLogPayloadCreate) SetRequestBodyBytes(v int) *RequestLogPayloadCreate {
	_c.mutation.SetRequestBodyBytes(v)
	return _c
}

// SetNillableRequestBodyBytes sets the "request_body_bytes" field if the given value is not nil.
func (_c *RequestLogPayloadCreate) SetNillableRequestBodyBytes(v *int) *RequestLogPayloadCreate {
	if v != nil {
		_c.SetRequestBodyBytes(*v)
	}
	return _c
}

// SetRequestBodyTruncated sets the "request_body_truncated" field.
func (_c *RequestLogPayloadCreate) SetRequestBodyTruncated(v bool) *RequestLogPayloadCreate {
	_c.mutation.SetRequestBodyTruncated(v)
	return _c
}

// SetNillableRequestBodyTruncated sets the "request_body_truncated" field if the given value is not nil.
func (_c *RequestLogPayloadCreate) SetNillableRequestBodyTruncated(v *bool) *RequestLogPayloadCreate {
	if v != nil {
		_c.SetRequestBodyTruncated(*v)
	}
	return _c
}

// SetResponseBody sets the "response_body" field.
func (_c *RequestLogPayloadCreate) SetResponseBody(v []byte) *RequestLogPayloadCreate {
	_c.mutation.SetResponseBody(v)
	return _c
}

// SetResponseBodyEncoding sets the "response_body_encoding" field.
func (_c *RequestLogPayloadCreate) SetResponseBodyEncoding(v string) *RequestLogPayloadCreate {
	_c.mutation.SetResponseBodyEncoding(v)
	return _c
}

// SetNillableResponseBodyEncoding sets the "response_body_encoding" field if the given value is not nil.
func (_c *RequestLogPayloadCreate) SetNillableResponseBodyEncoding(v *string) *RequestLogPayloadCreate {
	if v != nil {
		_c.SetResponseBodyEncoding(*v)
	}
	return _c
}

// SetResponseBodyBytes sets the "response_body_bytes" field.
func (_c *RequestLogPayloadCreate) SetResponseBodyBytes(v int) *RequestLogPayloadCreate {
	_c.mutation.SetResponseBodyBytes(v)
	return _c
}

// SetNillableResponseBodyBytes sets the "response_body_bytes" field if the given value is not nil.
func (_c *RequestLogPayloadCreate) SetNillableResponseBodyBytes(v *int) *RequestLogPayloadCreate {
	if v != nil {
		_c.SetResponseBodyBytes(*v)
	}
	return _c
}

// SetResponseBodyTruncated sets the "response_body_truncated" field.
func (_c *RequestLogPayloadCreate) SetResponseBodyTruncated(v bool) *RequestLogPayloadCreate {
	_c.mutation.SetResponseBodyTruncated(v)
	return _c
}

// SetNillableResponseBodyTruncated sets the "response_body_truncated" field if the given value is not nil.
func (_c *RequestLogPayloadCreate) SetNillableResponseBodyTruncated(v *bool) *RequestLogPayloadCreate {
	if v != nil {
		_c.SetResponseBodyTruncated(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RequestLogPayloadCreate) SetCreatedAt(v time.Time) *RequestLogPayloadCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RequestLogPayloadCreate) SetNillableCreatedAt(v *time.Time) *RequestLogPayloadCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetRequestLog sets the "request_log" edge to the RequestLog entity.
func (_c *RequestLogPayloadCreate) SetRequestLog(v *RequestLog) *RequestLogPayloadCreate {
	return _c.SetRequestLogID(v.ID)
}

// Mutation returns the RequestLogPayloadMutation object of the builder.
func (_c *RequestLogPayloadCreate) Mutation() *RequestLogPayloadMutation {
	return _c.mutation
}

// Save creates the RequestLogPayload in the database.
func (_c *RequestLogPayloadCreate) Save(ctx context.Context) (*RequestLogPayload, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RequestLogPayloadCreate) SaveX(ctx context.Context) *RequestLogPayload {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RequestLogPayloadCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RequestLogPayloadCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RequestLogPayloadCreate) defaults() {
	if _, ok := _c.mutation.RequestBodyTruncated(); !ok {
		v := requestlogpayload.DefaultRequestBodyTruncated
		_c.mutation.SetRequestBodyTruncated(v)
	}
	if _, ok := _c.mutation.ResponseBodyTruncated(); !ok {
		v := requestlogpayload.DefaultResponseBodyTruncated
		_c.mutation.SetResponseBodyTruncated(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := requestlogpayload.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RequestLogPayloadCreate) check() error {
	if _, ok := _c.mutation.RequestLogID(); !ok {
		return &ValidationError{Name: "request_log_id", err: errors.New(`ent: missing required field "RequestLogPayload.request_log_id"`)}
	}
	if v, ok := _c.mutation.RequestBodyEncoding(); ok {
		if err := requestlogpayload.RequestBodyEncodingValidator(v); err != nil {
			return &ValidationError{Name: "request_body_encoding", err: fmt.Errorf(`ent: validator failed for field "RequestLogPayload.request_body_encoding": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RequestBodyTruncated(); !ok {
		return &ValidationError{Name: "request_body_truncated", err: errors.New(`ent: missing required field "RequestLogPayload.request_body_truncated"`)}
	}
	if v, ok := _c.mutation.ResponseBodyEncoding(); ok {
		if err := requestlogpayload.ResponseBodyEncodingValidator(v); err != nil {
			return &ValidationError{Name: "response_body_encoding", err: fmt.Errorf(`ent: validator failed for field "RequestLogPayload.response_body_encoding": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ResponseBodyTruncated(); !ok {
		return &ValidationError{Name: "response_body_truncated", err: errors.New(`ent: missing required field "RequestLogPayload.response_body_truncated"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RequestLogPayload.created_at"`)}
	}
	if len(_c.mutation.RequestLogIDs()) == 0 {
		return &ValidationError{Name: "request_log", err: errors.New(`ent: missing required edge "RequestLogPayload.request_log"`)}
	}
	return nil
}

func (_c *RequestLogPayloadCreate) sqlSave(ctx context.Context) (*RequestLogPayload, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RequestLogPayloadCreate) createSpec() (*RequestLogPayload, *sqlgraph.CreateSpec) {
	var (
		_node = &RequestLogPayload{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(requestlogpayload.Table, sqlgraph.NewFieldSpec(requestlogpayload.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.RequestBody(); ok {
		_spec.SetField(requestlogpayload.FieldRequestBody, field.TypeBytes, value)
		_node.RequestBody = value
	}
	if value, ok := _c.mutation.RequestBodyEncoding(); ok {
		_spec.SetField(requestlogpayload.FieldRequestBodyEncoding, field.TypeString, value)
		_node.RequestBodyEncoding = &value
	}
	if value, ok := _c.mutation.RequestBodyBytes(); ok {
		_spec.SetField(requestlogpayload.FieldRequestBodyBytes, field.TypeInt, value)
		_node.RequestBodyBytes = &value
	}
	if value, ok := _c.mutation.RequestBodyTruncated(); ok {
		_spec.SetField(requestlogpayload.FieldRequestBodyTruncated, field.TypeBool, value)
		_node.RequestBodyTruncated = value
	}
	if value, ok := _c.mutation.ResponseBody(); ok {
		_spec.SetField(requestlogpayload.FieldResponseBody, field.TypeBytes, value)
		_node.ResponseBody = value
	}
	if value, ok := _c.mutation.ResponseBodyEncoding(); ok {
		_spec.SetField(requestlogpayload.FieldResponseBodyEncoding, field.TypeString, value)
		_node.ResponseBodyEncoding = &value
	}
	if value, ok := _c.mutation.ResponseBodyBytes(); ok {
		_spec.SetField(requestlogpayload.FieldResponseBodyBytes, field.TypeInt, value)
		_node.ResponseBodyBytes = &value
	}
	if value, ok := _c.mutation.ResponseBodyTruncated(); ok {
		_spec.SetField(requestlogpayload.FieldResponseBodyTruncated, field.TypeBool, value)
		_node.ResponseBodyTruncated = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(requestlogpayload.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.RequestLogIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   requestlogpayload.RequestLogTable,
			Columns: []string{requestlogpayload.RequestLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(requestlog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RequestLogID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RequestLogPayload.Create().
//		SetRequestLogID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RequestLogPayloadUpsert) {
//			SetRequestLogID(v+v).
//		}).
//		Exec(ctx)
func (_c *RequestLogPayloadCreate) OnConflict(opts ...sql.ConflictOption) *RequestLogPayloadUpsertOne {
	_c.conflict = opts
	return &RequestLogPayloadUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RequestLogPayload.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RequestLogPayloadCreate) OnConflictColumns(columns ...string) *RequestLogPayloadUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RequestLogPayloadUpsertOne{
		create: _c,
	}
}

type (
	// RequestLogPayloadUpsertOne is the builder for "upsert"-ing
	//  one RequestLogPayload node.
	RequestLogPayloadUpsertOne struct {
		create *RequestLogPayloadCreate
	}

	// RequestLogPayloadUpsert is the "OnConflict" setter.
	RequestLogPayloadUpsert struct {
		*sql.UpdateSet
	}
)

// SetRequestLogID sets the "request_log_id" field.
func (u *RequestLogPayloadUpsert) SetRequestLogID(v int64) *RequestLogPayloadUpsert {
	u.Set(requestlogpayload.FieldRequestLogID, v)
	return u
}

// UpdateRequestLogID sets the "request_log_id" field to the value that was provided on create.
func (u *RequestLogPayloadUpsert) UpdateRequestLogID() *RequestLogPayloadUpsert {
	u.SetExcluded(requestlogpayload.FieldRequestLogID)
	return u
}

// SetRequestBody sets the "request_body" field.
func (u *RequestLogPayloadUpsert) SetRequestBody(v []byte) *RequestLogPayloadUpsert {
	u.Set(requestlogpayload.FieldRequestBody, v)
	return u
}

// UpdateRequestBody sets the "request_body" field to the value that was provided on create.
func (u *RequestLogPayloadUpsert) UpdateRequestBody() *RequestLogPayloadUpsert {
	u.SetExcluded(requestlogpayload.FieldRequestBody)
	return u
}

// ClearRequestBody clears the value of the "request_body" field.
func (u *RequestLogPayloadUpsert) ClearRequestBody() *RequestLogPayloadUpsert {
	u.SetNull(requestlogpayload.FieldRequestBody)
	return u
}

// SetRequestBodyEncoding sets the "request_body_encoding" field.
func (u *RequestLogPayloadUpsert) SetRequestBodyEncoding(v string) *RequestLogPayloadUpsert {
	u.Set(requestlogpayload.FieldRequestBodyEncoding, v)
	return u
}

// UpdateRequestBodyEncoding sets the "request_body_encoding" field to the value that was provided on create.
func (u *RequestLogPayloadUpsert) UpdateRequestBodyEncoding() *RequestLogPayloadUpsert {
	u.SetExcluded(requestlogpayload.FieldRequestBodyEncoding)
	return u
}

// ClearRequestBodyEncoding clears the value of the "request_body_encoding" field.
func (u *RequestLogPayloadUpsert) ClearRequestBodyEncoding() *RequestLogPayloadUpsert {
	u.SetNull(requestlogpayload.FieldRequestBodyEncoding)
	return u
}

// SetRequestBodyBytes sets the "request_body_bytes" field.
func (u *RequestLogPayloadUpsert) SetRequestBodyBytes(v int) *RequestLogPayloadUpsert {
	u.Set(requestlogpayload.FieldRequestBodyBytes, v)
	return u
}

// UpdateRequestBodyBytes sets the "request_body_bytes" field to the value that was provided on create.
func (u *RequestLogPayloadUpsert) UpdateRequestBodyBytes() *RequestLogPayloadUpsert {
	u.SetExcluded(requestlogpayload.FieldRequestBodyBytes)
	return u
}

// AddRequestBodyBytes adds v to the "request_body_bytes" field.
func (u *RequestLogPayloadUpsert) AddRequestBodyBytes(v int) *RequestLogPayloadUpsert {
	u.Add(requestlogpayload.FieldRequestBodyBytes, v)
	return u
}

// ClearRequestBodyBytes clears the value of the "request_body_bytes" field.
func (u *RequestLogPayloadUpsert) ClearRequestBodyBytes() *RequestLogPayloadUpsert {
	u.SetNull(requestlogpayload.FieldRequestBodyBytes)
	return u
}

// SetRequestBodyTruncated sets the "request_body_truncated" field.
func (u *RequestLogPayloadUpsert) SetRequestBodyTruncated(v bool) *RequestLogPayloadUpsert {
	u.Set(requestlogpayload.FieldRequestBodyTruncated, v)
	return u
}

// UpdateRequestBodyTruncated sets the "request_body_truncated" field to the value that was provided on create.
func (u *RequestLogPayloadUpsert) UpdateRequestBodyTruncated() *RequestLogPayloadUpsert {
	u.SetExcluded(requestlogpayload.FieldRequestBodyTruncated)
	return u
}

// SetResponseBody sets the "response_body" field.
func (u *RequestLogPayloadUpsert) SetResponseBody(v []byte) *RequestLogPayloadUpsert {
	u.Set(requestlogpayload.FieldResponseBody, v)
	return u
}

// UpdateResponseBody sets the "response_body" field to the value that was provided on create.
func (u *RequestLogPayloadUpsert) UpdateResponseBody() *RequestLogPayloadUpsert {
	u.SetExcluded(requestlogpayload.FieldResponseBody)
	return u
}

// ClearResponseBody clears the value of the "response_body" field.
func (u *RequestLogPayloadUpsert) ClearResponseBody() *RequestLogPayloadUpsert {
	u.SetNull(requestlogpayload.FieldResponseBody)
	return u
}

// SetResponseBodyEncoding sets the "response_body_encoding" field.
func (u *RequestLogPayloadUpsert) SetResponseBodyEncoding(v string) *RequestLogPayloadUpsert {
	u.Set(requestlogpayload.FieldResponseBodyEncoding, v)
	return u
}

// UpdateResponseBodyEncoding sets the "response_body_encoding" field to the value that was provided on create.
func (u *RequestLogPayloadUpsert) UpdateResponseBodyEncoding() *RequestLogPayloadUpsert {
	u.SetExcluded(requestlogpayload.FieldResponseBodyEncoding)
	return u
}

// ClearResponseBodyEncoding clears the value of the "response_body_encoding" field.
func (u *RequestLogPayloadUpsert) ClearResponseBodyEncoding() *RequestLogPayloadUpsert {
	u.SetNull(requestlogpayload.FieldResponseBodyEncoding)
	return u
}

// SetResponseBodyBytes sets the "response_body_bytes" field.
func (u *RequestLogPayloadUpsert) SetResponseBodyBytes(v int) *RequestLogPayloadUpsert {
	u.Set(requestlogpayload.FieldResponseBodyBytes, v)
	return u
}

// UpdateResponseBodyBytes sets the "response_body_bytes" field to the value that was provided on create.
func (u *RequestLogPayloadUpsert) UpdateResponseBodyBytes() *RequestLogPayloadUpsert {
	u.SetExcluded(requestlogpayload.FieldResponseBodyBytes)
	return u
}

// AddResponseBodyBytes adds v to the "response_body_bytes" field.
func (u *RequestLogPayloadUpsert) AddResponseBodyBytes(v int) *RequestLogPayloadUpsert {
	u.Add(requestlogpayload.FieldResponseBodyBytes, v)
	return u
}

// ClearResponseBodyBytes clears the value of the "response_body_bytes" field.
func (u *RequestLogPayloadUpsert) ClearResponseBodyBytes() *RequestLogPayloadUpsert {
	u.SetNull(requestlogpayload.FieldResponseBodyBytes)
	return u
}

// SetResponseBodyTruncated sets the "response_body_truncated" field.
func (u *RequestLogPayloadUpsert) SetResponseBodyTruncated(v bool) *RequestLogPayloadUpsert {
	u.Set(requestlogpayload.FieldResponseBodyTruncated, v)
	return u
}

// UpdateResponseBodyTruncated sets the "response_body_truncated" field to the value that was provided on create.
func (u *RequestLogPayloadUpsert) UpdateResponseBodyTruncated() *RequestLogPayloadUpsert {
	u.SetExcluded(requestlogpayload.FieldResponseBodyTruncated)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.RequestLogPayload.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RequestLogPayloadUpsertOne) UpdateNewValues() *RequestLogPayloadUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(requestlogpayload.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RequestLogPayload.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RequestLogPayloadUpsertOne) Ignore() *RequestLogPayloadUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RequestLogPayloadUpsertOne) DoNothing() *RequestLogPayloadUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RequestLogPayloadCreate.OnConflict
// documentation for more info.
func (u *RequestLogPayloadUpsertOne) Update(set func(*RequestLogPayloadUpsert)) *RequestLogPayloadUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RequestLogPayloadUpsert{UpdateSet: update})
	}))
	return u
}

// SetRequestLogID sets the "request_log_id" field.
func (u *RequestLogPayloadUpsertOne) SetRequestLogID(v int64) *RequestLogPayloadUpsertOne {
	return u.Update(func(s *RequestLogPayloadUpsert) {
		s.SetRequestLogID(v)
	})
}

// UpdateRequestLogID sets the "request_log_id" field to the value that was provided on create.
func (u *RequestLogPayloadUpsertOne) UpdateRequestLogID() *RequestLogPayloadUpsertOne {
	return u.Update(func(s *RequestLogPayloadUpsert) {
		s.UpdateRequestLogID()
	})
}

// SetRequestBody sets the "request_body" field.
func (u *RequestLogPayloadUpsertOne) SetRequestBody(v []byte) *RequestLogPayloadUpsertOne {
	return u.Update(func(s *RequestLogPayloadUpsert) {
		s.SetRequestBody(v)
	})
}

// UpdateRequestBody sets the "request_body" field to the value that was provided on create.
func (u *RequestLogPayloadUpsertOne) UpdateRequestBody() *RequestLogPayloadUpsertOne {
	return u.Update(func(s *RequestLogPayloadUpsert) {
		s.UpdateRequestBody()
	})
}

// ClearRequestBody clears the value of the "request_body" field.
func (u *RequestLogPayloadUpsertOne) ClearRequestBody() *RequestLogPayloadUpsertOne {
	return u.Update(func(s *RequestLogPayloadUpsert) {
		s.ClearRequestBody()
	})
}

// SetRequestBodyEncoding sets the "request_body_encoding" field.
func (u *RequestLogPayloadUpsertOne) SetRequestBodyEncoding(v string) *RequestLogPayloadUpsertOne {
	return u.Update(func(s *RequestLogPayloadUpsert) {
		s.SetRequestBodyEncoding(v)
	})
}

// UpdateRequestBodyEncoding sets the "request_body_encoding" field to the value that was provided on create.
func (u *RequestLogPayloadUpsertOne) UpdateRequestBodyEncoding() *RequestLogPayloadUpsertOne {
	return u.Update(func(s *RequestLogPayloadUpsert) {
		s.UpdateRequestBodyEncoding()
	})
}

// ClearRequestBodyEncoding clears the value of the "request_body_encoding" field.
func (u *RequestLogPayloadUpsertOne) ClearRequestBodyEncoding() *RequestLogPayloadUpsertOne {
	return u.Update(func(s *RequestLogPayloadUpsert) {
		s.ClearRequestBodyEncoding()
	})
}

// SetRequestBodyBytes sets the "request_body_bytes" field.
func (u *RequestLogPayloadUpsertOne) SetRequestBodyBytes(v int) *RequestLogPayloadUpsertOne {
	return u.Update(func(s *RequestLogPayloadUpsert) {
		s.SetRequestBodyBytes(v)
	})
}

// AddRequestBodyBytes adds v to the "request_body_bytes" field.
func (u *RequestLogPayloadUpsertOne) AddRequestBodyBytes(v int) *RequestLogPayloadUpsertOne {
	return u.Update(func(s *RequestLogPayloadUpsert) {
		s.AddRequestBodyBytes(v)
	})
}

// UpdateRequestBodyBytes sets the "request_body_bytes" field to the value that was provided on create.
func (u *RequestLogPayloadUpsertOne) UpdateRequestBodyBytes() *RequestLogPayloadUpsertOne {
	return u.Update(func(s *RequestLogPayloadUpsert) {
		s.UpdateRequestBodyBytes()
	})
}

// ClearRequestBodyBytes clears the value of the "request_body_bytes" field.
func (u *RequestLogPayloadUpsertOne) ClearRequestBodyBytes() *RequestLogPayloadUpsertOne {
	return u.Update(func(s *RequestLogPayloadUpsert) {
		s.ClearRequestBodyBytes()
	})
}

// SetRequestBodyTruncated sets the "request_body_truncated" field.
func (u *RequestLogPayloadUpsertOne) SetRequestBodyTruncated(v bool) *RequestLogPayloadUpsertOne {
	return u.Update(func(s *RequestLogPayloadUpsert) {
		s.SetRequestBodyTruncated(v)
	})
}

// UpdateRequestBodyTruncated sets the "request_body_truncated" field to the value that was provided on create.
func (u *RequestLogPayloadUpsertOne) UpdateRequestBodyTruncated() *RequestLogPayloadUpsertOne {
	return u.Update(func(s *RequestLogPayloadUpsert) {
		s.UpdateRequestBodyTruncated()
	})
}

// SetResponseBody sets the "response_body" field.
func (u *RequestLogPayloadUpsertOne) SetResponseBody(v []byte) *RequestLogPayloadUpsertOne {
	return u.Update(func(s *RequestLogPayloadUpsert) {
		s.SetResponseBody(v)
	})
}

// UpdateResponseBody sets the "response_body" field to the value that was provided on create.
func (u *RequestLogPayloadUpsertOne) UpdateResponseBody() *RequestLogPayloadUpsertOne {
	return u.Update(func(s *RequestLogPayloadUpsert) {
		s.UpdateResponseBody()
	})
}

// ClearResponseBody clears the value of the "response_body" field.
func (u *RequestLogPayloadUpsertOne) ClearResponseBody() *RequestLogPayloadUpsertOne {
	return u.Update(func(s *RequestLogPayloadUpsert) {
		s.ClearResponseBody()
	})
}

// SetResponseBodyEncoding sets the "response_body_encoding" field.
func (u *RequestLogPayloadUpsertOne) SetResponseBodyEncoding(v string) *RequestLogPayloadUpsertOne {
	return u.Update(func(s *RequestLogPayloadUpsert) {
		s.SetResponseBodyEncoding(v)
	})
}

// UpdateResponseBodyEncoding sets the "response_body_encoding" field to the value that was provided on create.
func (u *RequestLogPayloadUpsertOne) UpdateResponseBodyEncoding() *RequestLogPayloadUpsertOne {
	return u.Update(func(s *RequestLogPayloadUpsert) {
		s.UpdateResponseBodyEncoding()
	})
}

// ClearResponseBodyEncoding clears the value of the "response_body_encoding" field.
func (u *RequestLogPayloadUpsertOne) ClearResponseBodyEncoding() *RequestLogPayloadUpsertOne {
	return u.Update(func(s *RequestLogPayloadUpsert) {
		s.ClearResponseBodyEncoding()
	})
}

// SetResponseBodyBytes sets the "response_body_bytes" field.
func (u *RequestLogPayloadUpsertOne) SetResponseBodyBytes(v int) *RequestLogPayloadUpsertOne {
	return u.Update(func(s *RequestLogPayloadUpsert) {
		s.SetResponseBodyBytes(v)
	})
}

// AddResponseBodyBytes adds v to the "response_body_bytes" field.
func (u *RequestLogPayloadUpsertOne) AddResponseBodyBytes(v int) *RequestLogPayloadUpsertOne {
	return u.Update(func(s *RequestLogPayloadUpsert) {
		s.AddResponseBodyBytes(v)
	})
}

// UpdateResponseBodyBytes sets the "response_body_bytes" field to the value that was provided on create.
func (u *RequestLogPayloadUpsertOne) UpdateResponseBodyBytes() *RequestLogPayloadUpsertOne {
	return u.Update(func(s *RequestLogPayloadUpsert) {
		s.UpdateResponseBodyBytes()
	})
}

// ClearResponseBodyBytes clears the value of the "response_body_bytes" field.
func (u *RequestLogPayloadUpsertOne) ClearResponseBodyBytes() *RequestLogPayloadUpsertOne {
	return u.Update(func(s *RequestLogPayloadUpsert) {
		s.ClearResponseBodyBytes()
	})
}

// SetResponseBodyTruncated sets the "response_body_truncated" field.
func (u *RequestLogPayloadUpsertOne) SetResponseBodyTruncated(v bool) *RequestLogPayloadUpsertOne {
	return u.Update(func(s *RequestLogPayloadUpsert) {
		s.SetResponseBodyTruncated(v)
	})
}

// UpdateResponseBodyTruncated sets the "response_body_truncated" field to the value that was provided on create.
func (u *RequestLogPayloadUpsertOne) UpdateResponseBodyTruncated() *RequestLogPayloadUpsertOne {
	return u.Update(func(s *RequestLogPayloadUpsert) {
		s.UpdateResponseBodyTruncated()
	})
}

// Exec executes the query.
func (u *RequestLogPayloadUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RequestLogPayloadCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RequestLogPayloadUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RequestLogPayloadUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RequestLogPayloadUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RequestLogPayloadCreateBulk is the builder for creating many RequestLogPayload entities in bulk.
type RequestLogPayloadCreateBulk struct {
	config
	err      error
	builders []*RequestLogPayloadCreate
	conflict []sql.ConflictOption
}

// Save creates the RequestLogPayload entities in the database.
func (_c *RequestLogPayloadCreateBulk) Save(ctx context.Context) ([]*RequestLogPayload, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RequestLogPayload, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RequestLogPayloadMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RequestLogPayloadCreateBulk) SaveX(ctx context.Context) []*RequestLogPayload {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RequestLogPayloadCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RequestLogPayloadCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RequestLogPayload.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RequestLogPayloadUpsert) {
//			SetRequestLogID(v+v).
//		}).
//		Exec(ctx)
func (_c *RequestLogPayloadCreateBulk) OnConflict(opts ...sql.ConflictOption) *RequestLogPayloadUpsertBulk {
	_c.conflict = opts
	return &RequestLogPayloadUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RequestLogPayload.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RequestLogPayloadCreateBulk) OnConflictColumns(columns ...string) *RequestLogPayloadUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RequestLogPayloadUpsertBulk{
		create: _c,
	}
}

// RequestLogPayloadUpsertBulk is the builder for "upsert"-ing
// a bulk of RequestLogPayload nodes.
type RequestLogPayloadUpsertBulk struct {
	create *RequestLogPayloadCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RequestLogPayload.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RequestLogPayloadUpsertBulk) UpdateNewValues() *RequestLogPayloadUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(requestlogpayload.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RequestLogPayload.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RequestLogPayloadUpsertBulk) Ignore() *RequestLogPayloadUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RequestLogPayloadUpsertBulk) DoNothing() *RequestLogPayloadUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RequestLogPayloadCreateBulk.OnConflict
// documentation for more info.
func (u *RequestLogPayloadUpsertBulk) Update(set func(*RequestLogPayloadUpsert)) *RequestLogPayloadUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RequestLogPayloadUpsert{UpdateSet: update})
	}))
	return u
}

// SetRequestLogID sets the "request_log_id" field.
func (u *RequestLogPayloadUpsertBulk) SetRequestLogID(v int64) *RequestLogPayloadUpsertBulk {
	return u.Update(func(s *RequestLogPayloadUpsert) {
		s.SetRequestLogID(v)
	})
}

// UpdateRequestLogID sets the "request_log_id" field to the value that was provided on create.
func (u *RequestLogPayloadUpsertBulk) UpdateRequestLogID() *RequestLogPayloadUpsertBulk {
	return u.Update(func(s *RequestLogPayloadUpsert) {
		s.UpdateRequestLogID()
	})
}

// SetRequestBody sets the "request_body" field.
func (u *RequestLogPayloadUpsertBulk) SetRequestBody(v []byte) *RequestLogPayloadUpsertBulk {
	return u.Update(func(s *RequestLogPayloadUpsert) {
		s.SetRequestBody(v)
	})
}

// UpdateRequestBody sets the "request_body" field to the value that was provided on create.
func (u *RequestLogPayloadUpsertBulk) UpdateRequestBody() *RequestLogPayloadUpsertBulk {
	return u.Update(func(s *RequestLogPayloadUpsert) {
		s.UpdateRequestBody()
	})
}

// ClearRequestBody clears the value of the "request_body" field.
func (u *RequestLogPayloadUpsertBulk) ClearRequestBody() *RequestLogPayloadUpsertBulk {
	return u.Update(func(s *RequestLogPayloadUpsert) {
		s.ClearRequestBody()
	})
}

// SetRequestBodyEncoding sets the "request_body_encoding" field.
func (u *RequestLogPayloadUpsertBulk) SetRequestBodyEncoding(v string) *RequestLogPayloadUpsertBulk {
	return u.Update(func(s *RequestLogPayloadUpsert) {
		s.SetRequestBodyEncoding(v)
	})
}

// UpdateRequestBodyEncoding sets the "request_body_encoding" field to the value that was provided on create.
func (u *RequestLogPayloadUpsertBulk) UpdateRequestBodyEncoding() *RequestLogPayloadUpsertBulk {
	return u.Update(func(s *RequestLogPayloadUpsert) {
		s.UpdateRequestBodyEncoding()
	})
}

// ClearRequestBodyEncoding clears the value of the "request_body_encoding" field.
func (u *RequestLogPayloadUpsertBulk) ClearRequestBodyEncoding() *RequestLogPayloadUpsertBulk {
	return u.Update(func(s *RequestLogPayloadUpsert) {
		s.ClearRequestBodyEncoding()
	})
}

// SetRequestBodyBytes sets the "request_body_bytes" field.
func (u *RequestLogPayloadUpsertBulk) SetRequestBodyBytes(v int) *RequestLogPayloadUpsertBulk {
	return u.Update(func(s *RequestLogPayloadUpsert) {
		s.SetRequestBodyBytes(v)
	})
}

// AddRequestBodyBytes adds v to the "request_body_bytes" field.
func (u *RequestLogPayloadUpsertBulk) AddRequestBodyBytes(v int) *RequestLogPayloadUpsertBulk {
	return u.Update(func(s *RequestLogPayloadUpsert) {
		s.AddRequestBodyBytes(v)
	})
}

// UpdateRequestBodyBytes sets the "request_body_bytes" field to the value that was provided on create.
func (u *RequestLogPayloadUpsertBulk) UpdateRequestBodyBytes() *RequestLogPayloadUpsertBulk {
	return u.Update(func(s *RequestLogPayloadUpsert) {
		s.UpdateRequestBodyBytes()
	})
}

// ClearRequestBodyBytes clears the value of the "request_body_bytes" field.
func (u *RequestLogPayloadUpsertBulk) ClearRequestBodyBytes() *RequestLogPayloadUpsertBulk {
	return u.Update(func(s *RequestLogPayloadUpsert) {
		s.ClearRequestBodyBytes()
	})
}

// SetRequestBodyTruncated sets the "request_body_truncated" field.
func (u *RequestLogPayloadUpsertBulk) SetRequestBodyTruncated(v bool) *RequestLogPayloadUpsertBulk {
	return u.Update(func(s *RequestLogPayloadUpsert) {
		s.SetRequestBodyTruncated(v)
	})
}

// UpdateRequestBodyTruncated sets the "request_body_truncated" field to the value that was provided on create.
func (u *RequestLogPayloadUpsertBulk) UpdateRequestBodyTruncated() *RequestLogPayloadUpsertBulk {
	return u.Update(func(s *RequestLogPayloadUpsert) {
		s.UpdateRequestBodyTruncated()
	})
}

// SetResponseBody sets the "response_body" field.
func (u *RequestLogPayloadUpsertBulk) SetResponseBody(v []byte) *RequestLogPayloadUpsertBulk {
	return u.Update(func(s *RequestLogPayloadUpsert) {
		s.SetResponseBody(v)
	})
}

// UpdateResponseBody sets the "response_body" field to the value that was provided on create.
func (u *RequestLogPayloadUpsertBulk) UpdateResponseBody() *RequestLogPayloadUpsertBulk {
	return u.Update(func(s *RequestLogPayloadUpsert) {
		s.UpdateResponseBody()
	})
}

// ClearResponseBody clears the value of the "response_body" field.
func (u *RequestLogPayloadUpsertBulk) ClearResponseBody() *RequestLogPayloadUpsertBulk {
	return u.Update(func(s *RequestLogPayloadUpsert) {
		s.ClearResponseBody()
	})
}

// SetResponseBodyEncoding sets the "response_body_encoding" field.
func (u *RequestLogPayloadUpsertBulk) SetResponseBodyEncoding(v string) *RequestLogPayloadUpsertBulk {
	return u.Update(func(s *RequestLogPayloadUpsert) {
		s.SetResponseBodyEncoding(v)
	})
}

// UpdateResponseBodyEncoding sets the "response_body_encoding" field to the value that was provided on create.
func (u *RequestLogPayloadUpsertBulk) UpdateResponseBodyEncoding() *RequestLogPayloadUpsertBulk {
	return u.Update(func(s *RequestLogPayloadUpsert) {
		s.UpdateResponseBodyEncoding()
	})
}

// ClearResponseBodyEncoding clears the value of the "response_body_encoding" field.
func (u *RequestLogPayloadUpsertBulk) ClearResponseBodyEncoding() *RequestLogPayloadUpsertBulk {
	return u.Update(func(s *RequestLogPayloadUpsert) {
		s.ClearResponseBodyEncoding()
	})
}

// SetResponseBodyBytes sets the "response_body_bytes" field.
func (u *RequestLogPayloadUpsertBulk) SetResponseBodyBytes(v int) *RequestLogPayloadUpsertBulk {
	return u.Update(func(s *RequestLogPayloadUpsert) {
		s.SetResponseBodyBytes(v)
	})
}

// AddResponseBodyBytes adds v to the "response_body_bytes" field.
func (u *RequestLogPayloadUpsertBulk) AddResponseBodyBytes(v int) *RequestLogPayloadUpsertBulk {
	return u.Update(func(s *RequestLogPayloadUpsert) {
		s.AddResponseBodyBytes(v)
	})
}

// UpdateResponseBodyBytes sets the "response_body_bytes" field to the value that was provided on create.
func (u *RequestLogPayloadUpsertBulk) UpdateResponseBodyBytes() *RequestLogPayloadUpsertBulk {
	return u.Update(func(s *RequestLogPayloadUpsert) {
		s.UpdateResponseBodyBytes()
	})
}

// ClearResponseBodyBytes clears the value of the "response_body_bytes" field.
func (u *RequestLogPayloadUpsertBulk) ClearResponseBodyBytes() *RequestLogPayloadUpsertBulk {
	return u.Update(func(s *RequestLogPayloadUpsert) {
		s.ClearResponseBodyBytes()
	})
}

// SetResponseBodyTruncated sets the "response_body_truncated" field.
func (u *RequestLogPayloadUpsertBulk) SetResponseBodyTruncated(v bool) *RequestLogPayloadUpsertBulk {
	return u.Update(func(s *RequestLogPayloadUpsert) {
		s.SetResponseBodyTruncated(v)
	})
}

// UpdateResponseBodyTruncated sets the "response_body_truncated" field to the value that was provided on create.
func (u *RequestLogPayloadUpsertBulk) UpdateResponseBodyTruncated() *RequestLogPayloadUpsertBulk {
	return u.Update(func(s *RequestLogPayloadUpsert) {
		s.UpdateResponseBodyTruncated()
	})
}

// Exec executes the query.
func (u *RequestLogPayloadUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RequestLogPayloadCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RequestLogPayloadCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RequestLogPayloadUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
