// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/requestlog"
	"github.com/Wei-Shaw/sub2api/ent/requestlogpayload"
)

// RequestLogPayloadUpdate is the builder for updating RequestLogPayload entities.
type RequestLogPayloadUpdate struct {
	config
	hooks    []Hook
	mutation *RequestLogPayloadMutation
}

// Where appends a list predicates to the RequestLogPayloadUpdate builder.
func (_u *RequestLogPayloadUpdate) Where(ps ...predicate.RequestLogPayload) *RequestLogPayloadUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRequestLogID sets the "request_log_id" field.
func (_u *RequestLogPayloadUpdate) SetRequestLogID(v int64) *RequestLogPayloadUpdate {
	_u.mutation.SetRequestLogID(v)
	return _u
}

// SetNillableRequestLogID sets the "request_log_id" field if the given value is not nil.
func (_u *RequestLogPayloadUpdate) SetNillableRequestLogID(v *int64) *RequestLogPayloadUpdate {
	if v != nil {
		_u.SetRequestLogID(*v)
	}
	return _u
}

// SetRequestBody sets the "request_body" field.
func (_u *RequestLogPayloadUpdate) SetRequestBody(v []byte) *RequestLogPayloadUpdate {
	_u.mutation.SetRequestBody(v)
	return _u
}

// ClearRequestBody clears the value of the "request_body" field.
func (_u *RequestLogPayloadUpdate) ClearRequestBody() *RequestLogPayloadUpdate {
	_u.mutation.ClearRequestBody()
	return _u
}

// SetRequestBodyEncoding sets the "request_body_encoding" field.
func (_u *RequestLogPayloadUpdate) SetRequestBodyEncoding(v string) *RequestLogPayloadUpdate {
	_u.mutation.SetRequestBodyEncoding(v)
	return _u
}

// SetNillableRequestBodyEncoding sets the "request_body_encoding" field if the given value is not nil.
func (_u *RequestLogPayloadUpdate) SetNillableRequestBodyEncoding(v *string) *RequestLogPayloadUpdate {
	if v != nil {
		_u.SetRequestBodyEncoding(*v)
	}
	return _u
}

// ClearRequestBodyEncoding clears the value of the "request_body_encoding" field.
func (_u *RequestLogPayloadUpdate) ClearRequestBodyEncoding() *RequestLogPayloadUpdate {
	_u.mutation.ClearRequestBodyEncoding()
	return _u
}

// SetRequestBodyBytes sets the "request_body_bytes" field.
func (_u *RequestLogPayloadUpdate) SetRequestBodyBytes(v int) *RequestLogPayloadUpdate {
	_u.mutation.ResetRequestBodyBytes()
	_u.mutation.SetRequestBodyBytes(v)
	return _u
}

// SetNillableRequestBodyBytes sets the "request_body_bytes" field if the given value is not nil.
func (_u *RequestLogPayloadUpdate) SetNillableRequestBodyBytes(v *int) *RequestLogPayloadUpdate {
	if v != nil {
		_u.SetRequestBodyBytes(*v)
	}
	return _u
}

// AddRequestBodyBytes adds value to the "request_body_bytes" field.
func (_u *RequestLogPayloadUpdate) AddRequestBodyBytes(v int) *RequestLogPayloadUpdate {
	_u.mutation.AddRequestBodyBytes(v)
	return _u
}

// ClearRequestBodyBytes clears the value of the "request_body_bytes" field.
func (_u *RequestLogPayloadUpdate) ClearRequestBodyBytes() *RequestLogPayloadUpdate {
	_u.mutation.ClearRequestBodyBytes()
	return _u
}

// SetRequestBodyTruncated sets the "request_body_truncated" field.
func (_u *RequestLogPayloadUpdate) SetRequestBodyTruncated(v bool) *RequestLogPayloadUpdate {
	_u.mutation.SetRequestBodyTruncated(v)
	return _u
}

// SetNillableRequestBodyTruncated sets the "request_body_truncated" field if the given value is not nil.
func (_u *RequestLogPayloadUpdate) SetNillableRequestBodyTruncated(v *bool) *RequestLogPayloadUpdate {
	if v != nil {
		_u.SetRequestBodyTruncated(*v)
	}
	return _u
}

// SetResponseBody sets the "response_body" field.
func (_u *RequestLogPayloadUpdate) SetResponseBody(v []byte) *RequestLogPayloadUpdate {
	_u.mutation.SetResponseBody(v)
	return _u
}

// ClearResponseBody clears the value of the "response_body" field.
func (_u *RequestLogPayloadUpdate) ClearResponseBody() *RequestLogPayloadUpdate {
	_u.mutation.ClearResponseBody()
	return _u
}

// SetResponseBodyEncoding sets the "response_body_encoding" field.
func (_u *RequestLogPayloadUpdate) SetResponseBodyEncoding(v string) *RequestLogPayloadUpdate {
	_u.mutation.SetResponseBodyEncoding(v)
	return _u
}

// SetNillableResponseBodyEncoding sets the "response_body_encoding" field if the given value is not nil.
func (_u *RequestLogPayloadUpdate) SetNillableResponseBodyEncoding(v *string) *RequestLogPayloadUpdate {
	if v != nil {
		_u.SetResponseBodyEncoding(*v)
	}
	return _u
}

// ClearResponseBodyEncoding clears the value of the "response_body_encoding" field.
func (_u *RequestLogPayloadUpdate) ClearResponseBodyEncoding() *RequestLogPayloadUpdate {
	_u.mutation.ClearResponseBodyEncoding()
	return _u
}

// SetResponseBodyBytes sets the "response_body_bytes" field.
func (_u *RequestLogPayloadUpdate) SetResponseBodyBytes(v int) *RequestLogPayloadUpdate {
	_u.mutation.ResetResponseBodyBytes()
	_u.mutation.SetResponseBodyBytes(v)
	return _u
}

// SetNillableResponseBodyBytes sets the "response_body_bytes" field if the given value is not nil.
func (_u *RequestLogPayloadUpdate) SetNillableResponseBodyBytes(v *int) *RequestLogPayloadUpdate {
	if v != nil {
		_u.SetResponseBodyBytes(*v)
	}
	return _u
}

// AddResponseBodyBytes adds value to the "response_body_bytes" field.
func (_u *RequestLogPayloadUpdate) AddResponseBodyBytes(v int) *RequestLogPayloadUpdate {
	_u.mutation.AddResponseBodyBytes(v)
	return _u
}

// ClearResponseBodyBytes clears the value of the "response_body_bytes" field.
func (_u *RequestLogPayloadUpdate) ClearResponseBodyBytes() *RequestLogPayloadUpdate {
	_u.mutation.ClearResponseBodyBytes()
	return _u
}

// SetResponseBodyTruncated sets the "response_body_truncated" field.
func (_u *RequestLogPayloadUpdate) SetResponseBodyTruncated(v bool) *RequestLogPayloadUpdate {
	_u.mutation.SetResponseBodyTruncated(v)
	return _u
}

// SetNillableResponseBodyTruncated sets the "response_body_truncated" field if the given value is not nil.
func (_u *RequestLogPayloadUpdate) SetNillableResponseBodyTruncated(v *bool) *RequestLogPayloadUpdate {
	if v != nil {
		_u.SetResponseBodyTruncated(*v)
	}
	return _u
}

// SetRequestLog sets the "request_log" edge to the RequestLog entity.
func (_u *RequestLogPayloadUpdate) SetRequestLog(v *RequestLog) *RequestLogPayloadUpdate {
	return _u.SetRequestLogID(v.ID)
}

// Mutation returns the RequestLogPayloadMutation object of the builder.
func (_u *RequestLogPayloadUpdate) Mutation() *RequestLogPayloadMutation {
	return _u.mutation
}

// ClearRequestLog clears the "request_log" edge to the RequestLog entity.
func (_u *RequestLogPayloadUpdate) ClearRequestLog() *RequestLogPayloadUpdate {
	_u.mutation.ClearRequestLog()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RequestLogPayloadUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RequestLogPayloadUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RequestLogPayloadUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RequestLogPayloadUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RequestLogPayloadUpdate) check() error {
	if v, ok := _u.mutation.RequestBodyEncoding(); ok {
		if err := requestlogpayload.RequestBodyEncodingValidator(v); err != nil {
			return &ValidationError{Name: "request_body_encoding", err: fmt.Errorf(`ent: validator failed for field "RequestLogPayload.request_body_encoding": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResponseBodyEncoding(); ok {
		if err := requestlogpayload.ResponseBodyEncodingValidator(v); err != nil {
			return &ValidationError{Name: "response_body_encoding", err: fmt.Errorf(`ent: validator failed for field "RequestLogPayload.response_body_encoding": %w`, err)}
		}
	}
	if _u.mutation.RequestLogCleared() && len(_u.mutation.RequestLogIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RequestLogPayload.request_log"`)
	}
	return nil
}

func (_u *RequestLogPayloadUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(requestlogpayload.Table, requestlogpayload.Columns, sqlgraph.NewFieldSpec(requestlogpayload.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RequestBody(); ok {
		_spec.SetField(requestlogpayload.FieldRequestBody, field.TypeBytes, value)
	}
	if _u.mutation.RequestBodyCleared() {
		_spec.ClearField(requestlogpayload.FieldRequestBody, field.TypeBytes)
	}
	if value, ok := _u.mutation.RequestBodyEncoding(); ok {
		_spec.SetField(requestlogpayload.FieldRequestBodyEncoding, field.TypeString, value)
	}
	if _u.mutation.RequestBodyEncodingCleared() {
		_spec.ClearField(requestlogpayload.FieldRequestBodyEncoding, field.TypeString)
	}
	if value, ok := _u.mutation.RequestBodyBytes(); ok {
		_spec.SetField(requestlogpayload.FieldRequestBodyBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRequestBodyBytes(); ok {
		_spec.AddField(requestlogpayload.FieldRequestBodyBytes, field.TypeInt, value)
	}
	if _u.mutation.RequestBodyBytesCleared() {
		_spec.ClearField(requestlogpayload.FieldRequestBodyBytes, field.TypeInt)
	}
	if value, ok := _u.mutation.RequestBodyTruncated(); ok {
		_spec.SetField(requestlogpayload.FieldRequestBodyTruncated, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ResponseBody(); ok {
		_spec.SetField(requestlogpayload.FieldResponseBody, field.TypeBytes, value)
	}
	if _u.mutation.ResponseBodyCleared() {
		_spec.ClearField(requestlogpayload.FieldResponseBody, field.TypeBytes)
	}
	if value, ok := _u.mutation.ResponseBodyEncoding(); ok {
		_spec.SetField(requestlogpayload.FieldResponseBodyEncoding, field.TypeString, value)
	}
	if _u.mutation.ResponseBodyEncodingCleared() {
		_spec.ClearField(requestlogpayload.FieldResponseBodyEncoding, field.TypeString)
	}
	if value, ok := _u.mutation.ResponseBodyBytes(); ok {
		_spec.SetField(requestlogpayload.FieldResponseBodyBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedResponseBodyBytes(); ok {
		_spec.AddField(requestlogpayload.FieldResponseBodyBytes, field.TypeInt, value)
	}
	if _u.mutation.ResponseBodyBytesCleared() {
		_spec.ClearField(requestlogpayload.FieldResponseBodyBytes, field.TypeInt)
	}
	if value, ok := _u.mutation.ResponseBodyTruncated(); ok {
		_spec.SetField(requestlogpayload.FieldResponseBodyTruncated, field.TypeBool, value)
	}
	if _u.mutation.RequestLogCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   requestlogpayload.RequestLogTable,
			Columns: []string{requestlogpayload.RequestLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(requestlog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RequestLogIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   requestlogpayload.RequestLogTable,
			Columns: []string{requestlogpayload.RequestLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(requestlog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{requestlogpayload.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RequestLogPayloadUpdateOne is the builder for updating a single RequestLogPayload entity.
type RequestLogPayloadUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RequestLogPayloadMutation
}

// SetRequestLogID sets the "request_log_id" field.
func (_u *RequestLogPayloadUpdateOne) SetRequestLogID(v int64) *RequestLogPayloadUpdateOne {
	_u.mutation.SetRequestLogID(v)
	return _u
}

// SetNillableRequestLogID sets the "request_log_id" field if the given value is not nil.
func (_u *RequestLogPayloadUpdateOne) SetNillableRequestLogID(v *int64) *RequestLogPayloadUpdateOne {
	if v != nil {
		_u.SetRequestLogID(*v)
	}
	return _u
}

// SetRequestBody sets the "request_body" field.
func (_u *RequestLogPayloadUpdateOne) SetRequestBody(v []byte) *RequestLogPayloadUpdateOne {
	_u.mutation.SetRequestBody(v)
	return _u
}

// ClearRequestBody clears the value of the "request_body" field.
func (_u *RequestLogPayloadUpdateOne) ClearRequestBody() *RequestLogPayloadUpdateOne {
	_u.mutation.ClearRequestBody()
	return _u
}

// SetRequestBodyEncoding sets the "request_body_encoding" field.
func (_u *RequestLogPayloadUpdateOne) SetRequestBodyEncoding(v string) *RequestLogPayloadUpdateOne {
	_u.mutation.SetRequestBodyEncoding(v)
	return _u
}

// SetNillableRequestBodyEncoding sets the "request_body_encoding" field if the given value is not nil.
func (_u *RequestLogPayloadUpdateOne) SetNillableRequestBodyEncoding(v *string) *RequestLogPayloadUpdateOne {
	if v != nil {
		_u.SetRequestBodyEncoding(*v)
	}
	return _u
}

// ClearRequestBodyEncoding clears the value of the "request_body_encoding" field.
func (_u *RequestLogPayloadUpdateOne) ClearRequestBodyEncoding() *RequestLogPayloadUpdateOne {
	_u.mutation.ClearRequestBodyEncoding()
	return _u
}

// SetRequestBodyBytes sets the "request_body_bytes" field.
func (_u *RequestLogPayloadUpdateOne) SetRequestBodyBytes(v int) *RequestLogPayloadUpdateOne {
	_u.mutation.ResetRequestBodyBytes()
	_u.mutation.SetRequestBodyBytes(v)
	return _u
}

// SetNillableRequestBodyBytes sets the "request_body_bytes" field if the given value is not nil.
func (_u *RequestLogPayloadUpdateOne) SetNillableRequestBodyBytes(v *int) *RequestLogPayloadUpdateOne {
	if v != nil {
		_u.SetRequestBodyBytes(*v)
	}
	return _u
}

// AddRequestBodyBytes adds value to the "request_body_bytes" field.
func (_u *RequestLogPayloadUpdateOne) AddRequestBodyBytes(v int) *RequestLogPayloadUpdateOne {
	_u.mutation.AddRequestBodyBytes(v)
	return _u
}

// ClearRequestBodyBytes clears the value of the "request_body_bytes" field.
func (_u *RequestLogPayloadUpdateOne) ClearRequestBodyBytes() *RequestLogPayloadUpdateOne {
	_u.mutation.ClearRequestBodyBytes()
	return _u
}

// SetRequestBodyTruncated sets the "request_body_truncated" field.
func (_u *RequestLogPayloadUpdateOne) SetRequestBodyTruncated(v bool) *RequestLogPayloadUpdateOne {
	_u.mutation.SetRequestBodyTruncated(v)
	return _u
}

// SetNillableRequestBodyTruncated sets the "request_body_truncated" field if the given value is not nil.
func (_u *RequestLogPayloadUpdateOne) SetNillableRequestBodyTruncated(v *bool) *RequestLogPayloadUpdateOne {
	if v != nil {
		_u.SetRequestBodyTruncated(*v)
	}
	return _u
}

// SetResponseBody sets the "response_body" field.
func (_u *RequestLogPayloadUpdateOne) SetResponseBody(v []byte) *RequestLogPayloadUpdateOne {
	_u.mutation.SetResponseBody(v)
	return _u
}

// ClearResponseBody clears the value of the "response_body" field.
func (_u *RequestLogPayloadUpdateOne) ClearResponseBody() *RequestLogPayloadUpdateOne {
	_u.mutation.ClearResponseBody()
	return _u
}

// SetResponseBodyEncoding sets the "response_body_encoding" field.
func (_u *RequestLogPayloadUpdateOne) SetResponseBodyEncoding(v string) *RequestLogPayloadUpdateOne {
	_u.mutation.SetResponseBodyEncoding(v)
	return _u
}

// SetNillableResponseBodyEncoding sets the "response_body_encoding" field if the given value is not nil.
func (_u *RequestLogPayloadUpdateOne) SetNillableResponseBodyEncoding(v *string) *RequestLogPayloadUpdateOne {
	if v != nil {
		_u.SetResponseBodyEncoding(*v)
	}
	return _u
}

// ClearResponseBodyEncoding clears the value of the "response_body_encoding" field.
func (_u *RequestLogPayloadUpdateOne) ClearResponseBodyEncoding() *RequestLogPayloadUpdateOne {
	_u.mutation.ClearResponseBodyEncoding()
	return _u
}

// SetResponseBodyBytes sets the "response_body_bytes" field.
func (_u *RequestLogPayloadUpdateOne) SetResponseBodyBytes(v int) *RequestLogPayloadUpdateOne {
	_u.mutation.ResetResponseBodyBytes()
	_u.mutation.SetResponseBodyBytes(v)
	return _u
}

// SetNillableResponseBodyBytes sets the "response_body_bytes" field if the given value is not nil.
func (_u *RequestLogPayloadUpdateOne) SetNillableResponseBodyBytes(v *int) *RequestLogPayloadUpdateOne {
	if v != nil {
		_u.SetResponseBodyBytes(*v)
	}
	return _u
}

// AddResponseBodyBytes adds value to the "response_body_bytes" field.
func (_u *RequestLogPayloadUpdateOne) AddResponseBodyBytes(v int) *RequestLogPayloadUpdateOne {
	_u.mutation.AddResponseBodyBytes(v)
	return _u
}

// ClearResponseBodyBytes clears the value of the "response_body_bytes" field.
func (_u *RequestLogPayloadUpdateOne) ClearResponseBodyBytes() *RequestLogPayloadUpdateOne {
	_u.mutation.ClearResponseBodyBytes()
	return _u
}

// SetResponseBodyTruncated sets the "response_body_truncated" field.
func (_u *RequestLogPayloadUpdateOne) SetResponseBodyTruncated(v bool) *RequestLogPayloadUpdateOne {
	_u.mutation.SetResponseBodyTruncated(v)
	return _u
}

// SetNillableResponseBodyTruncated sets the "response_body_truncated" field if the given value is not nil.
func (_u *RequestLogPayloadUpdateOne) SetNillableResponseBodyTruncated(v *bool) *RequestLogPayloadUpdateOne {
	if v != nil {
		_u.SetResponseBodyTruncated(*v)
	}
	return _u
}

// SetRequestLog sets the "request_log" edge to the RequestLog entity.
func (_u *RequestLogPayloadUpdateOne) SetRequestLog(v *RequestLog) *RequestLogPayloadUpdateOne {
	return _u.SetRequestLogID(v.ID)
}

// Mutation returns the RequestLogPayloadMutation object of the builder.
func (_u *RequestLogPayloadUpdateOne) Mutation() *RequestLogPayloadMutation {
	return _u.mutation
}

// ClearRequestLog clears the "request_log" edge to the RequestLog entity.
func (_u *RequestLogPayloadUpdateOne) ClearRequestLog() *RequestLogPayloadUpdateOne {
	_u.mutation.ClearRequestLog()
	return _u
}

// Where appends a list predicates to the RequestLogPayloadUpdate builder.
func (_u *RequestLogPayloadUpdateOne) Where(ps ...predicate.RequestLogPayload) *RequestLogPayloadUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RequestLogPayloadUpdateOne) Select(field string, fields ...string) *RequestLogPayloadUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RequestLogPayload entity.
func (_u *RequestLogPayloadUpdateOne) Save(ctx context.Context) (*RequestLogPayload, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RequestLogPayloadUpdateOne) SaveX(ctx context.Context) *RequestLogPayload {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RequestLogPayloadUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RequestLogPayloadUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RequestLogPayloadUpdateOne) check() error {
	if v, ok := _u.mutation.RequestBodyEncoding(); ok {
		if err := requestlogpayload.RequestBodyEncodingValidator(v); err != nil {
			return &ValidationError{Name: "request_body_encoding", err: fmt.Errorf(`ent: validator failed for field "RequestLogPayload.request_body_encoding": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResponseBodyEncoding(); ok {
		if err := requestlogpayload.ResponseBodyEncodingValidator(v); err != nil {
			return &ValidationError{Name: "response_body_encoding", err: fmt.Errorf(`ent: validator failed for field "RequestLogPayload.response_body_encoding": %w`, err)}
		}
	}
	if _u.mutation.RequestLogCleared() && len(_u.mutation.RequestLogIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RequestLogPayload.request_log"`)
	}
	return nil
}

func (_u *RequestLogPayloadUpdateOne) sqlSave(ctx context.Context) (_node *RequestLogPayload, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(requestlogpayload.Table, requestlogpayload.Columns, sqlgraph.NewFieldSpec(requestlogpayload.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RequestLogPayload.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, requestlogpayload.FieldID)
		for _, f := range fields {
			if !requestlogpayload.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != requestlogpayload.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RequestBody(); ok {
		_spec.SetField(requestlogpayload.FieldRequestBody, field.TypeBytes, value)
	}
	if _u.mutation.RequestBodyCleared() {
		_spec.ClearField(requestlogpayload.FieldRequestBody, field.TypeBytes)
	}
	if value, ok := _u.mutation.RequestBodyEncoding(); ok {
		_spec.SetField(requestlogpayload.FieldRequestBodyEncoding, field.TypeString, value)
	}
	if _u.mutation.RequestBodyEncodingCleared() {
		_spec.ClearField(requestlogpayload.FieldRequestBodyEncoding, field.TypeString)
	}
	if value, ok := _u.mutation.RequestBodyBytes(); ok {
		_spec.SetField(requestlogpayload.FieldRequestBodyBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRequestBodyBytes(); ok {
		_spec.AddField(requestlogpayload.FieldRequestBodyBytes, field.TypeInt, value)
	}
	if _u.mutation.RequestBodyBytesCleared() {
		_spec.ClearField(requestlogpayload.FieldRequestBodyBytes, field.TypeInt)
	}
	if value, ok := _u.mutation.RequestBodyTruncated(); ok {
		_spec.SetField(requestlogpayload.FieldRequestBodyTruncated, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ResponseBody(); ok {
		_spec.SetField(requestlogpayload.FieldResponseBody, field.TypeBytes, value)
	}
	if _u.mutation.ResponseBodyCleared() {
		_spec.ClearField(requestlogpayload.FieldResponseBody, field.TypeBytes)
	}
	if value, ok := _u.mutation.ResponseBodyEncoding(); ok {
		_spec.SetField(requestlogpayload.FieldResponseBodyEncoding, field.TypeString, value)
	}
	if _u.mutation.ResponseBodyEncodingCleared() {
		_spec.ClearField(requestlogpayload.FieldResponseBodyEncoding, field.TypeString)
	}
	if value, ok := _u.mutation.ResponseBodyBytes(); ok {
		_spec.SetField(requestlogpayload.FieldResponseBodyBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedResponseBodyBytes(); ok {
		_spec.AddField(requestlogpayload.FieldResponseBodyBytes, field.TypeInt, value)
	}
	if _u.mutation.ResponseBodyBytesCleared() {
		_spec.ClearField(requestlogpayload.FieldResponseBodyBytes, field.TypeInt)
	}
	if value, ok := _u.mutation.ResponseBodyTruncated(); ok {
		_spec.SetField(requestlogpayload.FieldResponseBodyTruncated, field.TypeBool, value)
	}
	if _u.mutation.RequestLogCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   requestlogpayload.RequestLogTable,
			Columns: []string{requestlogpayload.RequestLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(requestlog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RequestLogIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   requestlogpayload.RequestLogTable,
			Columns: []string{requestlogpayload.RequestLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(requestlog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RequestLogPayload{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{requestlogpayload.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
