// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/requestlogpayload"
)

// RequestLogPayloadDelete is the builder for deleting a RequestLogPayload entity.
type RequestLogPayloadDelete struct {
	config
	hooks    []Hook
	mutation *RequestLogPayloadMutation
}

// Where appends a list predicates to the RequestLogPayloadDelete builder.
func (_d *RequestLogPayloadDelete) Where(ps ...predicate.RequestLogPayload) *RequestLogPayloadDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *RequestLogPayloadDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RequestLogPayloadDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *RequestLogPayloadDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(requestlogpayload.Table, sqlgraph.NewFieldSpec(requestlogpayload.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// RequestLogPayloadDeleteOne is the builder for deleting a single RequestLogPayload entity.
type RequestLogPayloadDeleteOne struct {
	_d *RequestLogPayloadDelete
}

// Where appends a list predicates to the RequestLogPayloadDelete builder.
func (_d *RequestLogPayloadDeleteOne) Where(ps ...predicate.RequestLogPayload) *RequestLogPayloadDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *RequestLogPayloadDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{requestlogpayload.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RequestLogPayloadDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
