// Code generated by ent, DO NOT EDIT.

package requestlogpayload

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the requestlogpayload type in the database.
	Label = "request_log_payload"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRequestLogID holds the string denoting the request_log_id field in the database.
	FieldRequestLogID = "request_log_id"
	// FieldRequestBody holds the string denoting the request_body field in the database.
	FieldRequestBody = "request_body"
	// FieldRequestBodyEncoding holds the string denoting the request_body_encoding field in the database.
	FieldRequestBodyEncoding = "request_body_encoding"
	// FieldRequestBodyBytes holds the string denoting the request_body_bytes field in the database.
	FieldRequestBodyBytes = "request_body_bytes"
	// FieldRequestBodyTruncated holds the string denoting the request_body_truncated field in the database.
	FieldRequestBodyTruncated = "request_body_truncated"
	// FieldResponseBody holds the string denoting the response_body field in the database.
	FieldResponseBody = "response_body"
	// FieldResponseBodyEncoding holds the string denoting the response_body_encoding field in the database.
	FieldResponseBodyEncoding = "response_body_encoding"
	// FieldResponseBodyBytes holds the string denoting the response_body_bytes field in the database.
	FieldResponseBodyBytes = "response_body_bytes"
	// FieldResponseBodyTruncated holds the string denoting the response_body_truncated field in the database.
	FieldResponseBodyTruncated = "response_body_truncated"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeRequestLog holds the string denoting the request_log edge name in mutations.
	EdgeRequestLog = "request_log"
	// Table holds the table name of the requestlogpayload in the database.
	Table = "request_log_payloads"
	// RequestLogTable is the table that holds the request_log relation/edge.
	RequestLogTable = "request_log_payloads"
	// RequestLogInverseTable is the table name for the RequestLog entity.
	// It exists in this package in order to avoid circular dependency with the "requestlog" package.
	RequestLogInverseTable = "request_logs"
	// RequestLogColumn is the table column denoting the request_log relation/edge.
	RequestLogColumn = "request_log_id"
)

// Columns holds all SQL columns for requestlogpayload fields.
var Columns = []string{
	FieldID,
	FieldRequestLogID,
	FieldRequestBody,
	FieldRequestBodyEncoding,
	FieldRequestBodyBytes,
	FieldRequestBodyTruncated,
	FieldResponseBody,
	FieldResponseBodyEncoding,
	FieldResponseBodyBytes,
	FieldResponseBodyTruncated,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// RequestBodyEncodingValidator is a validator for the "request_body_encoding" field. It is called by the builders before save.
	RequestBodyEncodingValidator func(string) error
	// DefaultRequestBodyTruncated holds the default value on creation for the "request_body_truncated" field.
	DefaultRequestBodyTruncated bool
	// ResponseBodyEncodingValidator is a validator for the "response_body_encoding" field. It is called by the builders before save.
	ResponseBodyEncodingValidator func(string) error
	// DefaultResponseBodyTruncated holds the default value on creation for the "response_body_truncated" field.
	DefaultResponseBodyTruncated bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the RequestLogPayload queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRequestLogID orders the results by the request_log_id field.
func ByRequestLogID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestLogID, opts...).ToFunc()
}

// ByRequestBodyEncoding orders the results by the request_body_encoding field.
func ByRequestBodyEncoding(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestBodyEncoding, opts...).ToFunc()
}

// ByRequestBodyBytes orders the results by the request_body_bytes field.
func ByRequestBodyBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestBodyBytes, opts...).ToFunc()
}

// ByRequestBodyTruncated orders the results by the request_body_truncated field.
func ByRequestBodyTruncated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestBodyTruncated, opts...).ToFunc()
}

// ByResponseBodyEncoding orders the results by the response_body_encoding field.
func ByResponseBodyEncoding(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResponseBodyEncoding, opts...).ToFunc()
}

// ByResponseBodyBytes orders the results by the response_body_bytes field.
func ByResponseBodyBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResponseBodyBytes, opts...).ToFunc()
}

// ByResponseBodyTruncated orders the results by the response_body_truncated field.
func ByResponseBodyTruncated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResponseBodyTruncated, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByRequestLogField orders the results by request_log field.
func ByRequestLogField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRequestLogStep(), sql.OrderByField(field, opts...))
	}
}
func newRequestLogStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RequestLogInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, RequestLogTable, RequestLogColumn),
	)
}
