// Code generated by ent, DO NOT EDIT.

package requestlogpayload

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldLTE(FieldID, id))
}

// RequestLogID applies equality check predicate on the "request_log_id" field. It's identical to RequestLogIDEQ.
func RequestLogID(v int64) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldEQ(FieldRequestLogID, v))
}

// RequestBody applies equality check predicate on the "request_body" field. It's identical to RequestBodyEQ.
func RequestBody(v []byte) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldEQ(FieldRequestBody, v))
}

// RequestBodyEncoding applies equality check predicate on the "request_body_encoding" field. It's identical to RequestBodyEncodingEQ.
func RequestBodyEncoding(v string) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldEQ(FieldRequestBodyEncoding, v))
}

// RequestBodyBytes applies equality check predicate on the "request_body_bytes" field. It's identical to RequestBodyBytesEQ.
func RequestBodyBytes(v int) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldEQ(FieldRequestBodyBytes, v))
}

// RequestBodyTruncated applies equality check predicate on the "request_body_truncated" field. It's identical to RequestBodyTruncatedEQ.
func RequestBodyTruncated(v bool) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldEQ(FieldRequestBodyTruncated, v))
}

// ResponseBody applies equality check predicate on the "response_body" field. It's identical to ResponseBodyEQ.
func ResponseBody(v []byte) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldEQ(FieldResponseBody, v))
}

// ResponseBodyEncoding applies equality check predicate on the "response_body_encoding" field. It's identical to ResponseBodyEncodingEQ.
func ResponseBodyEncoding(v string) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldEQ(FieldResponseBodyEncoding, v))
}

// ResponseBodyBytes applies equality check predicate on the "response_body_bytes" field. It's identical to ResponseBodyBytesEQ.
func ResponseBodyBytes(v int) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldEQ(FieldResponseBodyBytes, v))
}

// ResponseBodyTruncated applies equality check predicate on the "response_body_truncated" field. It's identical to ResponseBodyTruncatedEQ.
func ResponseBodyTruncated(v bool) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldEQ(FieldResponseBodyTruncated, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldEQ(FieldCreatedAt, v))
}

// RequestLogIDEQ applies the EQ predicate on the "request_log_id" field.
func RequestLogIDEQ(v int64) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldEQ(FieldRequestLogID, v))
}

// RequestLogIDNEQ applies the NEQ predicate on the "request_log_id" field.
func RequestLogIDNEQ(v int64) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldNEQ(FieldRequestLogID, v))
}

// RequestLogIDIn applies the In predicate on the "request_log_id" field.
func RequestLogIDIn(vs ...int64) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldIn(FieldRequestLogID, vs...))
}

// RequestLogIDNotIn applies the NotIn predicate on the "request_log_id" field.
func RequestLogIDNotIn(vs ...int64) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldNotIn(FieldRequestLogID, vs...))
}

// RequestBodyEQ applies the EQ predicate on the "request_body" field.
func RequestBodyEQ(v []byte) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldEQ(FieldRequestBody, v))
}

// RequestBodyNEQ applies the NEQ predicate on the "request_body" field.
func RequestBodyNEQ(v []byte) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldNEQ(FieldRequestBody, v))
}

// RequestBodyIn applies the In predicate on the "request_body" field.
func RequestBodyIn(vs ...[]byte) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldIn(FieldRequestBody, vs...))
}

// RequestBodyNotIn applies the NotIn predicate on the "request_body" field.
func RequestBodyNotIn(vs ...[]byte) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldNotIn(FieldRequestBody, vs...))
}

// RequestBodyGT applies the GT predicate on the "request_body" field.
func RequestBodyGT(v []byte) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldGT(FieldRequestBody, v))
}

// RequestBodyGTE applies the GTE predicate on the "request_body" field.
func RequestBodyGTE(v []byte) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldGTE(FieldRequestBody, v))
}

// RequestBodyLT applies the LT predicate on the "request_body" field.
func RequestBodyLT(v []byte) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldLT(FieldRequestBody, v))
}

// RequestBodyLTE applies the LTE predicate on the "request_body" field.
func RequestBodyLTE(v []byte) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldLTE(FieldRequestBody, v))
}

// RequestBodyIsNil applies the IsNil predicate on the "request_body" field.
func RequestBodyIsNil() predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldIsNull(FieldRequestBody))
}

// RequestBodyNotNil applies the NotNil predicate on the "request_body" field.
func RequestBodyNotNil() predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldNotNull(FieldRequestBody))
}

// RequestBodyEncodingEQ applies the EQ predicate on the "request_body_encoding" field.
func RequestBodyEncodingEQ(v string) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldEQ(FieldRequestBodyEncoding, v))
}

// RequestBodyEncodingNEQ applies the NEQ predicate on the "request_body_encoding" field.
func RequestBodyEncodingNEQ(v string) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldNEQ(FieldRequestBodyEncoding, v))
}

// RequestBodyEncodingIn applies the In predicate on the "request_body_encoding" field.
func RequestBodyEncodingIn(vs ...string) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldIn(FieldRequestBodyEncoding, vs...))
}

// RequestBodyEncodingNotIn applies the NotIn predicate on the "request_body_encoding" field.
func RequestBodyEncodingNotIn(vs ...string) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldNotIn(FieldRequestBodyEncoding, vs...))
}

// RequestBodyEncodingGT applies the GT predicate on the "request_body_encoding" field.
func RequestBodyEncodingGT(v string) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldGT(FieldRequestBodyEncoding, v))
}

// RequestBodyEncodingGTE applies the GTE predicate on the "request_body_encoding" field.
func RequestBodyEncodingGTE(v string) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldGTE(FieldRequestBodyEncoding, v))
}

// RequestBodyEncodingLT applies the LT predicate on the "request_body_encoding" field.
func RequestBodyEncodingLT(v string) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldLT(FieldRequestBodyEncoding, v))
}

// RequestBodyEncodingLTE applies the LTE predicate on the "request_body_encoding" field.
func RequestBodyEncodingLTE(v string) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldLTE(FieldRequestBodyEncoding, v))
}

// RequestBodyEncodingContains applies the Contains predicate on the "request_body_encoding" field.
func RequestBodyEncodingContains(v string) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldContains(FieldRequestBodyEncoding, v))
}

// RequestBodyEncodingHasPrefix applies the HasPrefix predicate on the "request_body_encoding" field.
func RequestBodyEncodingHasPrefix(v string) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldHasPrefix(FieldRequestBodyEncoding, v))
}

// RequestBodyEncodingHasSuffix applies the HasSuffix predicate on the "request_body_encoding" field.
func RequestBodyEncodingHasSuffix(v string) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldHasSuffix(FieldRequestBodyEncoding, v))
}

// RequestBodyEncodingIsNil applies the IsNil predicate on the "request_body_encoding" field.
func RequestBodyEncodingIsNil() predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldIsNull(FieldRequestBodyEncoding))
}

// RequestBodyEncodingNotNil applies the NotNil predicate on the "request_body_encoding" field.
func RequestBodyEncodingNotNil() predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldNotNull(FieldRequestBodyEncoding))
}

// RequestBodyEncodingEqualFold applies the EqualFold predicate on the "request_body_encoding" field.
func RequestBodyEncodingEqualFold(v string) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldEqualFold(FieldRequestBodyEncoding, v))
}

// RequestBodyEncodingContainsFold applies the ContainsFold predicate on the "request_body_encoding" field.
func RequestBodyEncodingContainsFold(v string) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldContainsFold(FieldRequestBodyEncoding, v))
}

// RequestBodyBytesEQ applies the EQ predicate on the "request_body_bytes" field.
func RequestBodyBytesEQ(v int) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldEQ(FieldRequestBodyBytes, v))
}

// RequestBodyBytesNEQ applies the NEQ predicate on the "request_body_bytes" field.
func RequestBodyBytesNEQ(v int) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldNEQ(FieldRequestBodyBytes, v))
}

// RequestBodyBytesIn applies the In predicate on the "request_body_bytes" field.
func RequestBodyBytesIn(vs ...int) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldIn(FieldRequestBodyBytes, vs...))
}

// RequestBodyBytesNotIn applies the NotIn predicate on the "request_body_bytes" field.
func RequestBodyBytesNotIn(vs ...int) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldNotIn(FieldRequestBodyBytes, vs...))
}

// RequestBodyBytesGT applies the GT predicate on the "request_body_bytes" field.
func RequestBodyBytesGT(v int) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldGT(FieldRequestBodyBytes, v))
}

// RequestBodyBytesGTE applies the GTE predicate on the "request_body_bytes" field.
func RequestBodyBytesGTE(v int) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldGTE(FieldRequestBodyBytes, v))
}

// RequestBodyBytesLT applies the LT predicate on the "request_body_bytes" field.
func RequestBodyBytesLT(v int) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldLT(FieldRequestBodyBytes, v))
}

// RequestBodyBytesLTE applies the LTE predicate on the "request_body_bytes" field.
func RequestBodyBytesLTE(v int) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldLTE(FieldRequestBodyBytes, v))
}

// RequestBodyBytesIsNil applies the IsNil predicate on the "request_body_bytes" field.
func RequestBodyBytesIsNil() predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldIsNull(FieldRequestBodyBytes))
}

// RequestBodyBytesNotNil applies the NotNil predicate on the "request_body_bytes" field.
func RequestBodyBytesNotNil() predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldNotNull(FieldRequestBodyBytes))
}

// RequestBodyTruncatedEQ applies the EQ predicate on the "request_body_truncated" field.
func RequestBodyTruncatedEQ(v bool) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldEQ(FieldRequestBodyTruncated, v))
}

// RequestBodyTruncatedNEQ applies the NEQ predicate on the "request_body_truncated" field.
func RequestBodyTruncatedNEQ(v bool) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldNEQ(FieldRequestBodyTruncated, v))
}

// ResponseBodyEQ applies the EQ predicate on the "response_body" field.
func ResponseBodyEQ(v []byte) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldEQ(FieldResponseBody, v))
}

// ResponseBodyNEQ applies the NEQ predicate on the "response_body" field.
func ResponseBodyNEQ(v []byte) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldNEQ(FieldResponseBody, v))
}

// ResponseBodyIn applies the In predicate on the "response_body" field.
func ResponseBodyIn(vs ...[]byte) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldIn(FieldResponseBody, vs...))
}

// ResponseBodyNotIn applies the NotIn predicate on the "response_body" field.
func ResponseBodyNotIn(vs ...[]byte) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldNotIn(FieldResponseBody, vs...))
}

// ResponseBodyGT applies the GT predicate on the "response_body" field.
func ResponseBodyGT(v []byte) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldGT(FieldResponseBody, v))
}

// ResponseBodyGTE applies the GTE predicate on the "response_body" field.
func ResponseBodyGTE(v []byte) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldGTE(FieldResponseBody, v))
}

// ResponseBodyLT applies the LT predicate on the "response_body" field.
func ResponseBodyLT(v []byte) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldLT(FieldResponseBody, v))
}

// ResponseBodyLTE applies the LTE predicate on the "response_body" field.
func ResponseBodyLTE(v []byte) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldLTE(FieldResponseBody, v))
}

// ResponseBodyIsNil applies the IsNil predicate on the "response_body" field.
func ResponseBodyIsNil() predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldIsNull(FieldResponseBody))
}

// ResponseBodyNotNil applies the NotNil predicate on the "response_body" field.
func ResponseBodyNotNil() predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldNotNull(FieldResponseBody))
}

// ResponseBodyEncodingEQ applies the EQ predicate on the "response_body_encoding" field.
func ResponseBodyEncodingEQ(v string) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldEQ(FieldResponseBodyEncoding, v))
}

// ResponseBodyEncodingNEQ applies the NEQ predicate on the "response_body_encoding" field.
func ResponseBodyEncodingNEQ(v string) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldNEQ(FieldResponseBodyEncoding, v))
}

// ResponseBodyEncodingIn applies the In predicate on the "response_body_encoding" field.
func ResponseBodyEncodingIn(vs ...string) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldIn(FieldResponseBodyEncoding, vs...))
}

// ResponseBodyEncodingNotIn applies the NotIn predicate on the "response_body_encoding" field.
func ResponseBodyEncodingNotIn(vs ...string) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldNotIn(FieldResponseBodyEncoding, vs...))
}

// ResponseBodyEncodingGT applies the GT predicate on the "response_body_encoding" field.
func ResponseBodyEncodingGT(v string) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldGT(FieldResponseBodyEncoding, v))
}

// ResponseBodyEncodingGTE applies the GTE predicate on the "response_body_encoding" field.
func ResponseBodyEncodingGTE(v string) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldGTE(FieldResponseBodyEncoding, v))
}

// ResponseBodyEncodingLT applies the LT predicate on the "response_body_encoding" field.
func ResponseBodyEncodingLT(v string) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldLT(FieldResponseBodyEncoding, v))
}

// ResponseBodyEncodingLTE applies the LTE predicate on the "response_body_encoding" field.
func ResponseBodyEncodingLTE(v string) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldLTE(FieldResponseBodyEncoding, v))
}

// ResponseBodyEncodingContains applies the Contains predicate on the "response_body_encoding" field.
func ResponseBodyEncodingContains(v string) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldContains(FieldResponseBodyEncoding, v))
}

// ResponseBodyEncodingHasPrefix applies the HasPrefix predicate on the "response_body_encoding" field.
func ResponseBodyEncodingHasPrefix(v string) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldHasPrefix(FieldResponseBodyEncoding, v))
}

// ResponseBodyEncodingHasSuffix applies the HasSuffix predicate on the "response_body_encoding" field.
func ResponseBodyEncodingHasSuffix(v string) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldHasSuffix(FieldResponseBodyEncoding, v))
}

// ResponseBodyEncodingIsNil applies the IsNil predicate on the "response_body_encoding" field.
func ResponseBodyEncodingIsNil() predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldIsNull(FieldResponseBodyEncoding))
}

// ResponseBodyEncodingNotNil applies the NotNil predicate on the "response_body_encoding" field.
func ResponseBodyEncodingNotNil() predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldNotNull(FieldResponseBodyEncoding))
}

// ResponseBodyEncodingEqualFold applies the EqualFold predicate on the "response_body_encoding" field.
func ResponseBodyEncodingEqualFold(v string) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldEqualFold(FieldResponseBodyEncoding, v))
}

// ResponseBodyEncodingContainsFold applies the ContainsFold predicate on the "response_body_encoding" field.
func ResponseBodyEncodingContainsFold(v string) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldContainsFold(FieldResponseBodyEncoding, v))
}

// ResponseBodyBytesEQ applies the EQ predicate on the "response_body_bytes" field.
func ResponseBodyBytesEQ(v int) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldEQ(FieldResponseBodyBytes, v))
}

// ResponseBodyBytesNEQ applies the NEQ predicate on the "response_body_bytes" field.
func ResponseBodyBytesNEQ(v int) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldNEQ(FieldResponseBodyBytes, v))
}

// ResponseBodyBytesIn applies the In predicate on the "response_body_bytes" field.
func ResponseBodyBytesIn(vs ...int) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldIn(FieldResponseBodyBytes, vs...))
}

// ResponseBodyBytesNotIn applies the NotIn predicate on the "response_body_bytes" field.
func ResponseBodyBytesNotIn(vs ...int) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldNotIn(FieldResponseBodyBytes, vs...))
}

// ResponseBodyBytesGT applies the GT predicate on the "response_body_bytes" field.
func ResponseBodyBytesGT(v int) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldGT(FieldResponseBodyBytes, v))
}

// ResponseBodyBytesGTE applies the GTE predicate on the "response_body_bytes" field.
func ResponseBodyBytesGTE(v int) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldGTE(FieldResponseBodyBytes, v))
}

// ResponseBodyBytesLT applies the LT predicate on the "response_body_bytes" field.
func ResponseBodyBytesLT(v int) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldLT(FieldResponseBodyBytes, v))
}

// ResponseBodyBytesLTE applies the LTE predicate on the "response_body_bytes" field.
func ResponseBodyBytesLTE(v int) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldLTE(FieldResponseBodyBytes, v))
}

// ResponseBodyBytesIsNil applies the IsNil predicate on the "response_body_bytes" field.
func ResponseBodyBytesIsNil() predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldIsNull(FieldResponseBodyBytes))
}

// ResponseBodyBytesNotNil applies the NotNil predicate on the "response_body_bytes" field.
func ResponseBodyBytesNotNil() predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldNotNull(FieldResponseBodyBytes))
}

// ResponseBodyTruncatedEQ applies the EQ predicate on the "response_body_truncated" field.
func ResponseBodyTruncatedEQ(v bool) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldEQ(FieldResponseBodyTruncated, v))
}

// ResponseBodyTruncatedNEQ applies the NEQ predicate on the "response_body_truncated" field.
func ResponseBodyTruncatedNEQ(v bool) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldNEQ(FieldResponseBodyTruncated, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.FieldLTE(FieldCreatedAt, v))
}

// HasRequestLog applies the HasEdge predicate on the "request_log" edge.
func HasRequestLog() predicate.RequestLogPayload {
	return predicate.RequestLogPayload(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, RequestLogTable, RequestLogColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRequestLogWith applies the HasEdge predicate on the "request_log" edge with a given conditions (other predicates).
func HasRequestLogWith(preds ...predicate.RequestLog) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(func(s *sql.Selector) {
		step := newRequestLogStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RequestLogPayload) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RequestLogPayload) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RequestLogPayload) predicate.RequestLogPayload {
	return predicate.RequestLogPayload(sql.NotPredicates(p))
}
