// Code generated by ent, DO NOT EDIT.

package requestlog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldUserID, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldAPIKeyID, v))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldRequestID, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldModel, v))
}

// InboundEndpoint applies equality check predicate on the "inbound_endpoint" field. It's identical to InboundEndpointEQ.
func InboundEndpoint(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldInboundEndpoint, v))
}

// UpstreamEndpoint applies equality check predicate on the "upstream_endpoint" field. It's identical to UpstreamEndpointEQ.
func UpstreamEndpoint(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldUpstreamEndpoint, v))
}

// Method applies equality check predicate on the "method" field. It's identical to MethodEQ.
func Method(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldMethod, v))
}

// StatusCode applies equality check predicate on the "status_code" field. It's identical to StatusCodeEQ.
func StatusCode(v int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldStatusCode, v))
}

// ErrorCode applies equality check predicate on the "error_code" field. It's identical to ErrorCodeEQ.
func ErrorCode(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldErrorCode, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldErrorMessage, v))
}

// InputTokens applies equality check predicate on the "input_tokens" field. It's identical to InputTokensEQ.
func InputTokens(v int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldInputTokens, v))
}

// OutputTokens applies equality check predicate on the "output_tokens" field. It's identical to OutputTokensEQ.
func OutputTokens(v int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldOutputTokens, v))
}

// TotalCost applies equality check predicate on the "total_cost" field. It's identical to TotalCostEQ.
func TotalCost(v float64) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldTotalCost, v))
}

// Stream applies equality check predicate on the "stream" field. It's identical to StreamEQ.
func Stream(v bool) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldStream, v))
}

// DurationMs applies equality check predicate on the "duration_ms" field. It's identical to DurationMsEQ.
func DurationMs(v int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldDurationMs, v))
}

// FirstTokenMs applies equality check predicate on the "first_token_ms" field. It's identical to FirstTokenMsEQ.
func FirstTokenMs(v int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldFirstTokenMs, v))
}

// UserAgent applies equality check predicate on the "user_agent" field. It's identical to UserAgentEQ.
func UserAgent(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldUserAgent, v))
}

// IPAddress applies equality check predicate on the "ip_address" field. It's identical to IPAddressEQ.
func IPAddress(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldIPAddress, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldCreatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNotIn(FieldUserID, vs...))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDIsNil applies the IsNil predicate on the "request_id" field.
func RequestIDIsNil() predicate.RequestLog {
	return predicate.RequestLog(sql.FieldIsNull(FieldRequestID))
}

// RequestIDNotNil applies the NotNil predicate on the "request_id" field.
func RequestIDNotNil() predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNotNull(FieldRequestID))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldContainsFold(FieldRequestID, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldContainsFold(FieldModel, v))
}

// InboundEndpointEQ applies the EQ predicate on the "inbound_endpoint" field.
func InboundEndpointEQ(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldInboundEndpoint, v))
}

// InboundEndpointNEQ applies the NEQ predicate on the "inbound_endpoint" field.
func InboundEndpointNEQ(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNEQ(FieldInboundEndpoint, v))
}

// InboundEndpointIn applies the In predicate on the "inbound_endpoint" field.
func InboundEndpointIn(vs ...string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldIn(FieldInboundEndpoint, vs...))
}

// InboundEndpointNotIn applies the NotIn predicate on the "inbound_endpoint" field.
func InboundEndpointNotIn(vs ...string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNotIn(FieldInboundEndpoint, vs...))
}

// InboundEndpointGT applies the GT predicate on the "inbound_endpoint" field.
func InboundEndpointGT(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGT(FieldInboundEndpoint, v))
}

// InboundEndpointGTE applies the GTE predicate on the "inbound_endpoint" field.
func InboundEndpointGTE(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGTE(FieldInboundEndpoint, v))
}

// InboundEndpointLT applies the LT predicate on the "inbound_endpoint" field.
func InboundEndpointLT(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLT(FieldInboundEndpoint, v))
}

// InboundEndpointLTE applies the LTE predicate on the "inbound_endpoint" field.
func InboundEndpointLTE(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLTE(FieldInboundEndpoint, v))
}

// InboundEndpointContains applies the Contains predicate on the "inbound_endpoint" field.
func InboundEndpointContains(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldContains(FieldInboundEndpoint, v))
}

// InboundEndpointHasPrefix applies the HasPrefix predicate on the "inbound_endpoint" field.
func InboundEndpointHasPrefix(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldHasPrefix(FieldInboundEndpoint, v))
}

// InboundEndpointHasSuffix applies the HasSuffix predicate on the "inbound_endpoint" field.
func InboundEndpointHasSuffix(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldHasSuffix(FieldInboundEndpoint, v))
}

// InboundEndpointIsNil applies the IsNil predicate on the "inbound_endpoint" field.
func InboundEndpointIsNil() predicate.RequestLog {
	return predicate.RequestLog(sql.FieldIsNull(FieldInboundEndpoint))
}

// InboundEndpointNotNil applies the NotNil predicate on the "inbound_endpoint" field.
func InboundEndpointNotNil() predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNotNull(FieldInboundEndpoint))
}

// InboundEndpointEqualFold applies the EqualFold predicate on the "inbound_endpoint" field.
func InboundEndpointEqualFold(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEqualFold(FieldInboundEndpoint, v))
}

// InboundEndpointContainsFold applies the ContainsFold predicate on the "inbound_endpoint" field.
func InboundEndpointContainsFold(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldContainsFold(FieldInboundEndpoint, v))
}

// UpstreamEndpointEQ applies the EQ predicate on the "upstream_endpoint" field.
func UpstreamEndpointEQ(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldUpstreamEndpoint, v))
}

// UpstreamEndpointNEQ applies the NEQ predicate on the "upstream_endpoint" field.
func UpstreamEndpointNEQ(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNEQ(FieldUpstreamEndpoint, v))
}

// UpstreamEndpointIn applies the In predicate on the "upstream_endpoint" field.
func UpstreamEndpointIn(vs ...string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldIn(FieldUpstreamEndpoint, vs...))
}

// UpstreamEndpointNotIn applies the NotIn predicate on the "upstream_endpoint" field.
func UpstreamEndpointNotIn(vs ...string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNotIn(FieldUpstreamEndpoint, vs...))
}

// UpstreamEndpointGT applies the GT predicate on the "upstream_endpoint" field.
func UpstreamEndpointGT(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGT(FieldUpstreamEndpoint, v))
}

// UpstreamEndpointGTE applies the GTE predicate on the "upstream_endpoint" field.
func UpstreamEndpointGTE(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGTE(FieldUpstreamEndpoint, v))
}

// UpstreamEndpointLT applies the LT predicate on the "upstream_endpoint" field.
func UpstreamEndpointLT(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLT(FieldUpstreamEndpoint, v))
}

// UpstreamEndpointLTE applies the LTE predicate on the "upstream_endpoint" field.
func UpstreamEndpointLTE(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLTE(FieldUpstreamEndpoint, v))
}

// UpstreamEndpointContains applies the Contains predicate on the "upstream_endpoint" field.
func UpstreamEndpointContains(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldContains(FieldUpstreamEndpoint, v))
}

// UpstreamEndpointHasPrefix applies the HasPrefix predicate on the "upstream_endpoint" field.
func UpstreamEndpointHasPrefix(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldHasPrefix(FieldUpstreamEndpoint, v))
}

// UpstreamEndpointHasSuffix applies the HasSuffix predicate on the "upstream_endpoint" field.
func UpstreamEndpointHasSuffix(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldHasSuffix(FieldUpstreamEndpoint, v))
}

// UpstreamEndpointIsNil applies the IsNil predicate on the "upstream_endpoint" field.
func UpstreamEndpointIsNil() predicate.RequestLog {
	return predicate.RequestLog(sql.FieldIsNull(FieldUpstreamEndpoint))
}

// UpstreamEndpointNotNil applies the NotNil predicate on the "upstream_endpoint" field.
func UpstreamEndpointNotNil() predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNotNull(FieldUpstreamEndpoint))
}

// UpstreamEndpointEqualFold applies the EqualFold predicate on the "upstream_endpoint" field.
func UpstreamEndpointEqualFold(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEqualFold(FieldUpstreamEndpoint, v))
}

// UpstreamEndpointContainsFold applies the ContainsFold predicate on the "upstream_endpoint" field.
func UpstreamEndpointContainsFold(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldContainsFold(FieldUpstreamEndpoint, v))
}

// MethodEQ applies the EQ predicate on the "method" field.
func MethodEQ(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldMethod, v))
}

// MethodNEQ applies the NEQ predicate on the "method" field.
func MethodNEQ(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNEQ(FieldMethod, v))
}

// MethodIn applies the In predicate on the "method" field.
func MethodIn(vs ...string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldIn(FieldMethod, vs...))
}

// MethodNotIn applies the NotIn predicate on the "method" field.
func MethodNotIn(vs ...string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNotIn(FieldMethod, vs...))
}

// MethodGT applies the GT predicate on the "method" field.
func MethodGT(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGT(FieldMethod, v))
}

// MethodGTE applies the GTE predicate on the "method" field.
func MethodGTE(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGTE(FieldMethod, v))
}

// MethodLT applies the LT predicate on the "method" field.
func MethodLT(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLT(FieldMethod, v))
}

// MethodLTE applies the LTE predicate on the "method" field.
func MethodLTE(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLTE(FieldMethod, v))
}

// MethodContains applies the Contains predicate on the "method" field.
func MethodContains(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldContains(FieldMethod, v))
}

// MethodHasPrefix applies the HasPrefix predicate on the "method" field.
func MethodHasPrefix(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldHasPrefix(FieldMethod, v))
}

// MethodHasSuffix applies the HasSuffix predicate on the "method" field.
func MethodHasSuffix(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldHasSuffix(FieldMethod, v))
}

// MethodIsNil applies the IsNil predicate on the "method" field.
func MethodIsNil() predicate.RequestLog {
	return predicate.RequestLog(sql.FieldIsNull(FieldMethod))
}

// MethodNotNil applies the NotNil predicate on the "method" field.
func MethodNotNil() predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNotNull(FieldMethod))
}

// MethodEqualFold applies the EqualFold predicate on the "method" field.
func MethodEqualFold(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEqualFold(FieldMethod, v))
}

// MethodContainsFold applies the ContainsFold predicate on the "method" field.
func MethodContainsFold(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldContainsFold(FieldMethod, v))
}

// StatusCodeEQ applies the EQ predicate on the "status_code" field.
func StatusCodeEQ(v int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldStatusCode, v))
}

// StatusCodeNEQ applies the NEQ predicate on the "status_code" field.
func StatusCodeNEQ(v int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNEQ(FieldStatusCode, v))
}

// StatusCodeIn applies the In predicate on the "status_code" field.
func StatusCodeIn(vs ...int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldIn(FieldStatusCode, vs...))
}

// StatusCodeNotIn applies the NotIn predicate on the "status_code" field.
func StatusCodeNotIn(vs ...int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNotIn(FieldStatusCode, vs...))
}

// StatusCodeGT applies the GT predicate on the "status_code" field.
func StatusCodeGT(v int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGT(FieldStatusCode, v))
}

// StatusCodeGTE applies the GTE predicate on the "status_code" field.
func StatusCodeGTE(v int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGTE(FieldStatusCode, v))
}

// StatusCodeLT applies the LT predicate on the "status_code" field.
func StatusCodeLT(v int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLT(FieldStatusCode, v))
}

// StatusCodeLTE applies the LTE predicate on the "status_code" field.
func StatusCodeLTE(v int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLTE(FieldStatusCode, v))
}

// StatusCodeIsNil applies the IsNil predicate on the "status_code" field.
func StatusCodeIsNil() predicate.RequestLog {
	return predicate.RequestLog(sql.FieldIsNull(FieldStatusCode))
}

// StatusCodeNotNil applies the NotNil predicate on the "status_code" field.
func StatusCodeNotNil() predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNotNull(FieldStatusCode))
}

// ErrorCodeEQ applies the EQ predicate on the "error_code" field.
func ErrorCodeEQ(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldErrorCode, v))
}

// ErrorCodeNEQ applies the NEQ predicate on the "error_code" field.
func ErrorCodeNEQ(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNEQ(FieldErrorCode, v))
}

// ErrorCodeIn applies the In predicate on the "error_code" field.
func ErrorCodeIn(vs ...string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldIn(FieldErrorCode, vs...))
}

// ErrorCodeNotIn applies the NotIn predicate on the "error_code" field.
func ErrorCodeNotIn(vs ...string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNotIn(FieldErrorCode, vs...))
}

// ErrorCodeGT applies the GT predicate on the "error_code" field.
func ErrorCodeGT(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGT(FieldErrorCode, v))
}

// ErrorCodeGTE applies the GTE predicate on the "error_code" field.
func ErrorCodeGTE(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGTE(FieldErrorCode, v))
}

// ErrorCodeLT applies the LT predicate on the "error_code" field.
func ErrorCodeLT(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLT(FieldErrorCode, v))
}

// ErrorCodeLTE applies the LTE predicate on the "error_code" field.
func ErrorCodeLTE(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLTE(FieldErrorCode, v))
}

// ErrorCodeContains applies the Contains predicate on the "error_code" field.
func ErrorCodeContains(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldContains(FieldErrorCode, v))
}

// ErrorCodeHasPrefix applies the HasPrefix predicate on the "error_code" field.
func ErrorCodeHasPrefix(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldHasPrefix(FieldErrorCode, v))
}

// ErrorCodeHasSuffix applies the HasSuffix predicate on the "error_code" field.
func ErrorCodeHasSuffix(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldHasSuffix(FieldErrorCode, v))
}

// ErrorCodeIsNil applies the IsNil predicate on the "error_code" field.
func ErrorCodeIsNil() predicate.RequestLog {
	return predicate.RequestLog(sql.FieldIsNull(FieldErrorCode))
}

// ErrorCodeNotNil applies the NotNil predicate on the "error_code" field.
func ErrorCodeNotNil() predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNotNull(FieldErrorCode))
}

// ErrorCodeEqualFold applies the EqualFold predicate on the "error_code" field.
func ErrorCodeEqualFold(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEqualFold(FieldErrorCode, v))
}

// ErrorCodeContainsFold applies the ContainsFold predicate on the "error_code" field.
func ErrorCodeContainsFold(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldContainsFold(FieldErrorCode, v))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.RequestLog {
	return predicate.RequestLog(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldContainsFold(FieldErrorMessage, v))
}

// InputTokensEQ applies the EQ predicate on the "input_tokens" field.
func InputTokensEQ(v int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldInputTokens, v))
}

// InputTokensNEQ applies the NEQ predicate on the "input_tokens" field.
func InputTokensNEQ(v int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNEQ(FieldInputTokens, v))
}

// InputTokensIn applies the In predicate on the "input_tokens" field.
func InputTokensIn(vs ...int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldIn(FieldInputTokens, vs...))
}

// InputTokensNotIn applies the NotIn predicate on the "input_tokens" field.
func InputTokensNotIn(vs ...int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNotIn(FieldInputTokens, vs...))
}

// InputTokensGT applies the GT predicate on the "input_tokens" field.
func InputTokensGT(v int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGT(FieldInputTokens, v))
}

// InputTokensGTE applies the GTE predicate on the "input_tokens" field.
func InputTokensGTE(v int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGTE(FieldInputTokens, v))
}

// InputTokensLT applies the LT predicate on the "input_tokens" field.
func InputTokensLT(v int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLT(FieldInputTokens, v))
}

// InputTokensLTE applies the LTE predicate on the "input_tokens" field.
func InputTokensLTE(v int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLTE(FieldInputTokens, v))
}

// OutputTokensEQ applies the EQ predicate on the "output_tokens" field.
func OutputTokensEQ(v int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldOutputTokens, v))
}

// OutputTokensNEQ applies the NEQ predicate on the "output_tokens" field.
func OutputTokensNEQ(v int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNEQ(FieldOutputTokens, v))
}

// OutputTokensIn applies the In predicate on the "output_tokens" field.
func OutputTokensIn(vs ...int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldIn(FieldOutputTokens, vs...))
}

// OutputTokensNotIn applies the NotIn predicate on the "output_tokens" field.
func OutputTokensNotIn(vs ...int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNotIn(FieldOutputTokens, vs...))
}

// OutputTokensGT applies the GT predicate on the "output_tokens" field.
func OutputTokensGT(v int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGT(FieldOutputTokens, v))
}

// OutputTokensGTE applies the GTE predicate on the "output_tokens" field.
func OutputTokensGTE(v int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGTE(FieldOutputTokens, v))
}

// OutputTokensLT applies the LT predicate on the "output_tokens" field.
func OutputTokensLT(v int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLT(FieldOutputTokens, v))
}

// OutputTokensLTE applies the LTE predicate on the "output_tokens" field.
func OutputTokensLTE(v int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLTE(FieldOutputTokens, v))
}

// TotalCostEQ applies the EQ predicate on the "total_cost" field.
func TotalCostEQ(v float64) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldTotalCost, v))
}

// TotalCostNEQ applies the NEQ predicate on the "total_cost" field.
func TotalCostNEQ(v float64) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNEQ(FieldTotalCost, v))
}

// TotalCostIn applies the In predicate on the "total_cost" field.
func TotalCostIn(vs ...float64) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldIn(FieldTotalCost, vs...))
}

// TotalCostNotIn applies the NotIn predicate on the "total_cost" field.
func TotalCostNotIn(vs ...float64) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNotIn(FieldTotalCost, vs...))
}

// TotalCostGT applies the GT predicate on the "total_cost" field.
func TotalCostGT(v float64) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGT(FieldTotalCost, v))
}

// TotalCostGTE applies the GTE predicate on the "total_cost" field.
func TotalCostGTE(v float64) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGTE(FieldTotalCost, v))
}

// TotalCostLT applies the LT predicate on the "total_cost" field.
func TotalCostLT(v float64) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLT(FieldTotalCost, v))
}

// TotalCostLTE applies the LTE predicate on the "total_cost" field.
func TotalCostLTE(v float64) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLTE(FieldTotalCost, v))
}

// StreamEQ applies the EQ predicate on the "stream" field.
func StreamEQ(v bool) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldStream, v))
}

// StreamNEQ applies the NEQ predicate on the "stream" field.
func StreamNEQ(v bool) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNEQ(FieldStream, v))
}

// DurationMsEQ applies the EQ predicate on the "duration_ms" field.
func DurationMsEQ(v int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldDurationMs, v))
}

// DurationMsNEQ applies the NEQ predicate on the "duration_ms" field.
func DurationMsNEQ(v int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNEQ(FieldDurationMs, v))
}

// DurationMsIn applies the In predicate on the "duration_ms" field.
func DurationMsIn(vs ...int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldIn(FieldDurationMs, vs...))
}

// DurationMsNotIn applies the NotIn predicate on the "duration_ms" field.
func DurationMsNotIn(vs ...int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNotIn(FieldDurationMs, vs...))
}

// DurationMsGT applies the GT predicate on the "duration_ms" field.
func DurationMsGT(v int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGT(FieldDurationMs, v))
}

// DurationMsGTE applies the GTE predicate on the "duration_ms" field.
func DurationMsGTE(v int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGTE(FieldDurationMs, v))
}

// DurationMsLT applies the LT predicate on the "duration_ms" field.
func DurationMsLT(v int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLT(FieldDurationMs, v))
}

// DurationMsLTE applies the LTE predicate on the "duration_ms" field.
func DurationMsLTE(v int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLTE(FieldDurationMs, v))
}

// DurationMsIsNil applies the IsNil predicate on the "duration_ms" field.
func DurationMsIsNil() predicate.RequestLog {
	return predicate.RequestLog(sql.FieldIsNull(FieldDurationMs))
}

// DurationMsNotNil applies the NotNil predicate on the "duration_ms" field.
func DurationMsNotNil() predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNotNull(FieldDurationMs))
}

// FirstTokenMsEQ applies the EQ predicate on the "first_token_ms" field.
func FirstTokenMsEQ(v int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldFirstTokenMs, v))
}

// FirstTokenMsNEQ applies the NEQ predicate on the "first_token_ms" field.
func FirstTokenMsNEQ(v int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNEQ(FieldFirstTokenMs, v))
}

// FirstTokenMsIn applies the In predicate on the "first_token_ms" field.
func FirstTokenMsIn(vs ...int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldIn(FieldFirstTokenMs, vs...))
}

// FirstTokenMsNotIn applies the NotIn predicate on the "first_token_ms" field.
func FirstTokenMsNotIn(vs ...int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNotIn(FieldFirstTokenMs, vs...))
}

// FirstTokenMsGT applies the GT predicate on the "first_token_ms" field.
func FirstTokenMsGT(v int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGT(FieldFirstTokenMs, v))
}

// FirstTokenMsGTE applies the GTE predicate on the "first_token_ms" field.
func FirstTokenMsGTE(v int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGTE(FieldFirstTokenMs, v))
}

// FirstTokenMsLT applies the LT predicate on the "first_token_ms" field.
func FirstTokenMsLT(v int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLT(FieldFirstTokenMs, v))
}

// FirstTokenMsLTE applies the LTE predicate on the "first_token_ms" field.
func FirstTokenMsLTE(v int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLTE(FieldFirstTokenMs, v))
}

// FirstTokenMsIsNil applies the IsNil predicate on the "first_token_ms" field.
func FirstTokenMsIsNil() predicate.RequestLog {
	return predicate.RequestLog(sql.FieldIsNull(FieldFirstTokenMs))
}

// FirstTokenMsNotNil applies the NotNil predicate on the "first_token_ms" field.
func FirstTokenMsNotNil() predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNotNull(FieldFirstTokenMs))
}

// UserAgentEQ applies the EQ predicate on the "user_agent" field.
func UserAgentEQ(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldUserAgent, v))
}

// UserAgentNEQ applies the NEQ predicate on the "user_agent" field.
func UserAgentNEQ(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNEQ(FieldUserAgent, v))
}

// UserAgentIn applies the In predicate on the "user_agent" field.
func UserAgentIn(vs ...string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldIn(FieldUserAgent, vs...))
}

// UserAgentNotIn applies the NotIn predicate on the "user_agent" field.
func UserAgentNotIn(vs ...string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNotIn(FieldUserAgent, vs...))
}

// UserAgentGT applies the GT predicate on the "user_agent" field.
func UserAgentGT(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGT(FieldUserAgent, v))
}

// UserAgentGTE applies the GTE predicate on the "user_agent" field.
func UserAgentGTE(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGTE(FieldUserAgent, v))
}

// UserAgentLT applies the LT predicate on the "user_agent" field.
func UserAgentLT(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLT(FieldUserAgent, v))
}

// UserAgentLTE applies the LTE predicate on the "user_agent" field.
func UserAgentLTE(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLTE(FieldUserAgent, v))
}

// UserAgentContains applies the Contains predicate on the "user_agent" field.
func UserAgentContains(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldContains(FieldUserAgent, v))
}

// UserAgentHasPrefix applies the HasPrefix predicate on the "user_agent" field.
func UserAgentHasPrefix(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldHasPrefix(FieldUserAgent, v))
}

// UserAgentHasSuffix applies the HasSuffix predicate on the "user_agent" field.
func UserAgentHasSuffix(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldHasSuffix(FieldUserAgent, v))
}

// UserAgentIsNil applies the IsNil predicate on the "user_agent" field.
func UserAgentIsNil() predicate.RequestLog {
	return predicate.RequestLog(sql.FieldIsNull(FieldUserAgent))
}

// UserAgentNotNil applies the NotNil predicate on the "user_agent" field.
func UserAgentNotNil() predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNotNull(FieldUserAgent))
}

// UserAgentEqualFold applies the EqualFold predicate on the "user_agent" field.
func UserAgentEqualFold(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEqualFold(FieldUserAgent, v))
}

// UserAgentContainsFold applies the ContainsFold predicate on the "user_agent" field.
func UserAgentContainsFold(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldContainsFold(FieldUserAgent, v))
}

// IPAddressEQ applies the EQ predicate on the "ip_address" field.
func IPAddressEQ(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldIPAddress, v))
}

// IPAddressNEQ applies the NEQ predicate on the "ip_address" field.
func IPAddressNEQ(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNEQ(FieldIPAddress, v))
}

// IPAddressIn applies the In predicate on the "ip_address" field.
func IPAddressIn(vs ...string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldIn(FieldIPAddress, vs...))
}

// IPAddressNotIn applies the NotIn predicate on the "ip_address" field.
func IPAddressNotIn(vs ...string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNotIn(FieldIPAddress, vs...))
}

// IPAddressGT applies the GT predicate on the "ip_address" field.
func IPAddressGT(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGT(FieldIPAddress, v))
}

// IPAddressGTE applies the GTE predicate on the "ip_address" field.
func IPAddressGTE(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGTE(FieldIPAddress, v))
}

// IPAddressLT applies the LT predicate on the "ip_address" field.
func IPAddressLT(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLT(FieldIPAddress, v))
}

// IPAddressLTE applies the LTE predicate on the "ip_address" field.
func IPAddressLTE(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLTE(FieldIPAddress, v))
}

// IPAddressContains applies the Contains predicate on the "ip_address" field.
func IPAddressContains(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldContains(FieldIPAddress, v))
}

// IPAddressHasPrefix applies the HasPrefix predicate on the "ip_address" field.
func IPAddressHasPrefix(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldHasPrefix(FieldIPAddress, v))
}

// IPAddressHasSuffix applies the HasSuffix predicate on the "ip_address" field.
func IPAddressHasSuffix(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldHasSuffix(FieldIPAddress, v))
}

// IPAddressIsNil applies the IsNil predicate on the "ip_address" field.
func IPAddressIsNil() predicate.RequestLog {
	return predicate.RequestLog(sql.FieldIsNull(FieldIPAddress))
}

// IPAddressNotNil applies the NotNil predicate on the "ip_address" field.
func IPAddressNotNil() predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNotNull(FieldIPAddress))
}

// IPAddressEqualFold applies the EqualFold predicate on the "ip_address" field.
func IPAddressEqualFold(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEqualFold(FieldIPAddress, v))
}

// IPAddressContainsFold applies the ContainsFold predicate on the "ip_address" field.
func IPAddressContainsFold(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldContainsFold(FieldIPAddress, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.RequestLog {
	return predicate.RequestLog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.RequestLog {
	return predicate.RequestLog(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAPIKey applies the HasEdge predicate on the "api_key" edge.
func HasAPIKey() predicate.RequestLog {
	return predicate.RequestLog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, APIKeyTable, APIKeyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAPIKeyWith applies the HasEdge predicate on the "api_key" edge with a given conditions (other predicates).
func HasAPIKeyWith(preds ...predicate.APIKey) predicate.RequestLog {
	return predicate.RequestLog(func(s *sql.Selector) {
		step := newAPIKeyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RequestLog) predicate.RequestLog {
	return predicate.RequestLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RequestLog) predicate.RequestLog {
	return predicate.RequestLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RequestLog) predicate.RequestLog {
	return predicate.RequestLog(sql.NotPredicates(p))
}
